/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Vendor identifier (e.g., 'my-company.com')
 */
export type Vendor = string;
/**
 * Library name (e.g., 'processing')
 */
export type Library = string;
/**
 * IP core name (e.g., 'my_timer_core')
 */
export type Name = string;
/**
 * Version string (e.g., '1.2.0')
 */
export type Version = string;
/**
 * IP core description
 */
export type Description = string;
/**
 * Physical port name (HDL)
 */
export type Name1 = string;
/**
 * Standard logical name for association
 */
export type Logicalname = string;
/**
 * Port direction enumeration.
 */
export type PortDirection = 'in' | 'out' | 'inout';
/**
 * Port width in bits or parameter name
 */
export type Width = number | string;
/**
 * VHDL type (e.g. std_logic, std_logic_vector)
 */
export type Type = string;
/**
 * Port description
 */
export type Description1 = string;
/**
 * Clock frequency (e.g., '100MHz')
 */
export type Frequency = string | null;
/**
 * Clock definitions
 */
export type Clocks = Clock[];
/**
 * Physical port name (HDL)
 */
export type Name2 = string;
/**
 * Standard logical name for association
 */
export type Logicalname1 = string;
/**
 * Port direction enumeration.
 */
export type PortDirection1 = 'in' | 'out' | 'inout';
/**
 * Port width in bits or parameter name
 */
export type Width1 = number | string;
/**
 * VHDL type (e.g. std_logic, std_logic_vector)
 */
export type Type1 = string;
/**
 * Port description
 */
export type Description2 = string;
/**
 * Reset polarity (activeHigh or activeLow)
 */
export type Polarity = 'activeHigh' | 'activeLow';
/**
 * Reset definitions
 */
export type Resets = Reset[];
/**
 * Physical port name (HDL)
 */
export type Name3 = string;
/**
 * Standard logical name for association
 */
export type Logicalname2 = string;
/**
 * Port direction enumeration.
 */
export type PortDirection2 = 'in' | 'out' | 'inout';
/**
 * Port width in bits or parameter name
 */
export type Width2 = number | string;
/**
 * Interrupt sensitivity (LEVEL_HIGH, LEVEL_LOW, EDGE_RISING, EDGE_FALLING)
 */
export type Sensitivity = 'LEVEL_HIGH' | 'LEVEL_LOW' | 'EDGE_RISING' | 'EDGE_FALLING';
/**
 * Interrupt signal description
 */
export type Description3 = string;
/**
 * Interrupt output definitions
 */
export type Interrupts = Interrupt[];
/**
 * Physical port name (HDL)
 */
export type Name4 = string;
/**
 * Standard logical name for association
 */
export type Logicalname3 = string;
/**
 * Port direction enumeration.
 */
export type PortDirection3 = 'in' | 'out' | 'inout';
/**
 * Port width in bits or parameter name
 */
export type Width3 = number | string;
/**
 * VHDL type (e.g. std_logic, std_logic_vector)
 */
export type Type2 = string;
/**
 * Port description
 */
export type Description4 = string;
/**
 * Data/control ports
 */
export type Ports = Port[];
/**
 * Logical interface name
 */
export type Name5 = string;
/**
 * Bus type identifier: a full VLNV in vendor:library:name:version format (e.g., 'ipcraft:busif:axi4_lite:1.0'), or a recognized short alias (e.g., 'AXI4L').
 */
export type Type3 = string;
/**
 * Interface mode: 'master' or 'slave'
 */
export type BusInterfaceMode = 'master' | 'slave' | 'source' | 'sink' | 'conduit';
/**
 * Prefix for physical port names (e.g., 's_axi_')
 */
export type Physicalprefix = string;
/**
 * Logical clock name this interface uses
 */
export type Associatedclock = string | null;
/**
 * Logical reset name this interface uses
 */
export type Associatedreset = string | null;
/**
 * Memory map name for register access
 */
export type Memorymapref = string | null;
/**
 * List of optional ports to include
 */
export type Useoptionalports = string[];
/**
 * Number of instances
 */
export type Count = number;
/**
 * Starting index
 */
export type Indexstart = number;
/**
 * Naming pattern with {index} placeholder (e.g., 'M_AXIS_CH{index}_EVENTS')
 */
export type Namingpattern = string;
/**
 * Physical prefix pattern with {index} placeholder
 */
export type Physicalprefixpattern = string;
/**
 * Interface description
 */
export type Description5 = string;
/**
 * User-defined signals for conduit (custom) interfaces
 */
export type ConduitPorts = ConduitPort[] | null;
/**
 * Port name (HDL signal name)
 */
export type Name6 = string;
/**
 * Port direction enumeration.
 */
export type PortDirection4 = 'in' | 'out' | 'inout';
/**
 * Port width in bits or parameter name
 */
export type Width4 = number | string;
/**
 * Optional port description
 */
export type Description6 = string | null;
/**
 * Whether the port is required or optional in the generated interface
 */
export type Presence = ('required' | 'optional') | null;
/**
 * Bus interface definitions
 */
export type Businterfaces = BusInterface[];
/**
 * Memory map name
 */
export type Name7 = string;
/**
 * Memory map description
 */
export type Description7 = string;
/**
 * Block name
 */
export type Name8 = string;
/**
 * Block starting address
 */
export type Baseaddress = number | null;
/**
 * Block size (bytes or '4K', '1M', etc.)
 */
export type Range = number | string | null;
/**
 * Block usage type
 */
export type BlockUsage = 'register' | 'memory' | 'reserved';
/**
 * Default access
 */
export type AccessType =
  | 'read-only'
  | 'write-only'
  | 'read-write'
  | 'write-1-to-clear'
  | 'read-write-1-to-clear'
  | 'write-self-clearing'
  | 'read-write-self-clearing';
/**
 * Block description
 */
export type Description8 = string;
/**
 * Default register width
 */
export type Defaultregwidth = number;
/**
 * Register name
 */
export type Name9 = string;
/**
 * Offset from address block base
 */
export type Offset = number | null;
/**
 * Register width in bits
 */
export type Size = number;
/**
 * Default access type
 */
export type AccessType1 =
  | 'read-only'
  | 'write-only'
  | 'read-write'
  | 'write-1-to-clear'
  | 'read-write-1-to-clear'
  | 'write-self-clearing'
  | 'read-write-self-clearing';
/**
 * Reset value for entire register
 */
export type Resetvalue = number | null;
/**
 * Register description
 */
export type Description9 = string;
/**
 * Bit field name
 */
export type Name10 = string;
/**
 * Starting bit position (LSB = 0)
 */
export type Offset1 = number | null;
/**
 * Number of bits
 */
export type Width5 = number | null;
/**
 * Bit range string e.g. [7:0]
 */
export type Bits = string | null;
/**
 * Access type
 */
export type AccessType2 =
  | 'read-only'
  | 'write-only'
  | 'read-write'
  | 'write-1-to-clear'
  | 'read-write-1-to-clear'
  | 'write-self-clearing'
  | 'read-write-self-clearing';
/**
 * Reset/default value
 */
export type Resetvalue1 = number | null;
/**
 * Field description
 */
export type Description10 = string;
/**
 * Enumeration mapping {value: name}
 */
export type Enumeratedvalues = {
  [k: string]: string;
} | null;
/**
 * Bit fields
 */
export type Fields = BitFieldDef[];
/**
 * Child registers (for groups)
 */
export type Registers1 = RegisterDef[];
/**
 * Array replication count
 */
export type Count1 = number | null;
/**
 * Array replication stride
 */
export type Stride = number | null;
/**
 * Registers in block
 */
export type Registers = RegisterDef[];
/**
 * Address blocks
 */
export type Addressblocks = AddressBlock[];
/**
 * File set name
 */
export type Name11 = string;
/**
 * File set description
 */
export type Description11 = string;
/**
 * Whether the file should be overwritten on generation
 */
export type Managed = boolean;
/**
 * Relative or absolute file path
 */
export type Path = string;
/**
 * File type
 */
export type FileType =
  | 'vhdl'
  | 'verilog'
  | 'systemverilog'
  | 'xdc'
  | 'sdc'
  | 'ucf'
  | 'cHeader'
  | 'cSource'
  | 'cppHeader'
  | 'cppSource'
  | 'python'
  | 'makefile'
  | 'pdf'
  | 'markdown'
  | 'text'
  | 'tcl'
  | 'yaml'
  | 'json'
  | 'xml'
  | 'unknown';
/**
 * File description
 */
export type Description12 = string;
/**
 * Whether file is an include file
 */
export type Isincludefile = boolean;
/**
 * Logical name (e.g., library name for VHDL)
 */
export type Logicalname4 = string;
/**
 * Files in this set
 */
export type Files = File[];
/**
 * File sets
 */
export type Filesets = FileSet[];
/**
 * Parameter name
 */
export type Name12 = string;
/**
 * Data type
 */
export type ParameterType = 'integer' | 'boolean' | 'string';
/**
 * Parameter description
 */
export type Description13 = string;
/**
 * Generics/parameters
 */
export type Parameters = Parameter[];

/**
 * Complete IP core definition - the single source of truth.
 *
 * This is the canonical data model that all parsers produce and
 * all generators consume. It includes:
 * - Metadata (VLNV, description)
 * - Interface definitions (clocks, resets, ports, buses)
 * - Memory maps (registers, bit fields)
 * - Files (HDL sources, constraints, documentation)
 * - Parameters/generics
 */
export interface IpCore {
  vlnv: VLNV;
  description?: Description;
  clocks?: Clocks;
  resets?: Resets;
  interrupts?: Interrupts;
  ports?: Ports;
  busInterfaces?: Businterfaces;
  /**
   * Memory map definitions (inline array or external import)
   */
  memoryMaps?:
    | MemoryMap[]
    | {
        /**
         * Path to external memory map YAML file
         */
        import: string;
      };
  fileSets?: Filesets;
  parameters?: Parameters;
  subcores?: (string | { vlnv: string; path?: string })[];
}
/**
 * Unique identifier
 */
export interface VLNV {
  vendor: Vendor;
  library: Library;
  name: Name;
  version: Version;
  [k: string]: unknown;
}
/**
 * Clock definition for an IP core.
 *
 * Defines both logical (internal) and physical (port) names for clock signals.
 * Inherits from Port, typically with width=1.
 */
export interface Clock {
  name: Name1;
  logicalName?: Logicalname;
  direction?: PortDirection;
  width?: Width;
  type?: Type;
  description?: Description1;
  frequency?: Frequency;
  associatedReset?: string | null;
}
/**
 * Reset definition for an IP core.
 *
 * Defines both logical (internal) and physical (port) names for reset signals,
 * including polarity information.
 * Inherits from Port, typically with width=1.
 */
export interface Reset {
  name: Name2;
  logicalName?: Logicalname1;
  direction?: PortDirection1;
  width?: Width1;
  type?: Type1;
  description?: Description2;
  polarity?: Polarity;
  associatedClock?: string | null;
}
/**
 * Interrupt output definition for an IP core.
 *
 * Defines both logical (internal) and physical (port) names for interrupt signals.
 * Inherits from Port, typically with direction=out and width=1.
 */
export interface Interrupt {
  name: Name3;
  logicalName?: Logicalname2;
  direction?: PortDirection2;
  width?: Width2;
  sensitivity?: Sensitivity;
  description?: Description3;
}
/**
 * Generic port definition for IP cores.
 *
 * Used for data and control ports that are not part of clock, reset, or bus interfaces.
 */
export interface Port {
  name: Name4;
  logicalName?: Logicalname3;
  direction: PortDirection3;
  width?: Width3;
  type?: Type2;
  description?: Description4;
}
/**
 * Bus interface definition for an IP core.
 *
 * Represents a standardized bus connection (AXI, Avalon, etc.) with
 * optional width overrides, clock/reset associations, and array support.
 */
export interface BusInterface {
  name: Name5;
  type: Type3;
  mode: BusInterfaceMode;
  physicalPrefix: Physicalprefix;
  associatedClock?: Associatedclock;
  associatedReset?: Associatedreset;
  memoryMapRef?: Memorymapref;
  useOptionalPorts?: Useoptionalports;
  portWidthOverrides?: Portwidthoverrides;
  /** Logical-signal-name → physical suffix overrides, used when physical port names
   *  deviate from the physicalPrefix + logicalName.toLowerCase() convention. */
  portNameOverrides?: Record<string, string>;
  /**
   * Logical port names (uppercase) that are required by the bus spec but absent from the
   * user's HDL source. Populated automatically by the VHDL parser; prevents the generator
   * from emitting ports not present in the entity.
   */
  absentPorts?: string[];
  /**
   * Array configuration for multiple instances
   */
  array?: ArrayConfig | null;
  description?: Description5;
  conduitPorts?: ConduitPorts;
}
/**
 * Port width overrides {port_name: width_or_parameter_name}
 */
export interface Portwidthoverrides {
  [k: string]: number | string;
}
/**
 * Configuration for array of bus interfaces.
 *
 * Enables creation of multiple interface instances (e.g., 4 AXI Stream channels).
 */
export interface ArrayConfig {
  count: Count;
  indexStart?: Indexstart;
  namingPattern: Namingpattern;
  physicalPrefixPattern: Physicalprefixpattern;
}
/**
 * A single signal within a conduit (custom) bus interface.
 */
export interface ConduitPort {
  name: Name6;
  /**
   * Port direction
   */
  direction?: PortDirection4;
  width?: Width4;
  description?: Description6;
  presence?: Presence;
}
/**
 * Complete memory map for an IP core (Pydantic model).
 *
 * Organizes registers into address blocks with validation.
 */
export interface MemoryMap {
  name: Name7;
  description?: Description7;
  addressBlocks?: Addressblocks;
}
/**
 * Contiguous address block within a memory map (Pydantic model).
 *
 * Can contain registers, memory, or reserved space.
 */
export interface AddressBlock {
  name: Name8;
  baseAddress?: Baseaddress;
  range?: Range;
  usage?: BlockUsage;
  access?: AccessType;
  description?: Description8;
  defaultRegWidth?: Defaultregwidth;
  registers?: Registers;
  [k: string]: unknown;
}
/**
 * Register definition within a memory map (Pydantic model for YAML parsing).
 *
 * Represents a memory-mapped register with bit fields.
 */
export interface RegisterDef {
  name: Name9;
  offset?: Offset;
  size?: Size;
  access?: AccessType1;
  resetValue?: Resetvalue;
  description?: Description9;
  fields?: Fields;
  registers?: Registers1;
  count?: Count1;
  stride?: Stride;
  [k: string]: unknown;
}
/**
 * Bit field definition within a register (Pydantic model for YAML parsing).
 *
 * Represents a named range of bits with specific access semantics.
 */
export interface BitFieldDef {
  name: Name10;
  offset?: Offset1;
  width?: Width5;
  bits?: Bits;
  access?: AccessType2;
  resetValue?: Resetvalue1;
  description?: Description10;
  enumeratedValues?: Enumeratedvalues;
  [k: string]: unknown;
}
/**
 * Named collection of files for an IP core.
 *
 * Groups related files together (e.g., RTL sources, C API, documentation).
 */
export interface FileSet {
  name: Name11;
  description?: Description11;
  files?: Files;
}
/**
 * File reference within a file set.
 *
 * Represents a file that is part of the IP core (source, constraint, doc, etc.).
 */
export interface File {
  managed?: Managed;
  path: Path;
  type: FileType;
  description?: Description12;
  isIncludeFile?: Isincludefile;
  logicalName?: Logicalname4;
}
/**
 * Generic parameter/generic definition for IP cores.
 *
 * Used for VHDL generics, Verilog parameters, or component configuration.
 */
export interface Parameter {
  name: Name12;
  value: Value;
  dataType?: ParameterType;
  description?: Description13;
}
/**
 * Default value
 */
export interface Value {
  [k: string]: unknown;
}
