/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Memory map name
 */
export type Name = string;
/**
 * Memory map description
 */
export type Description = string;
/**
 * Block name
 */
export type Name1 = string;
/**
 * Block starting address
 */
export type Baseaddress = number | null;
/**
 * Block size (bytes or '4K', '1M', etc.)
 */
export type Range = number | string | null;
/**
 * Block usage type
 */
export type BlockUsage = "register" | "memory" | "reserved";
/**
 * Default access
 */
export type AccessType = "read-only" | "write-only" | "read-write" | "write-1-to-clear" | "read-write-1-to-clear";
/**
 * Block description
 */
export type Description1 = string;
/**
 * Default register width
 */
export type Defaultregwidth = number;
/**
 * Register name
 */
export type Name2 = string;
/**
 * Offset from address block base
 */
export type Offset = number | null;
/**
 * Register width in bits
 */
export type Size = number;
/**
 * Default access type
 */
export type AccessType1 = "read-only" | "write-only" | "read-write" | "write-1-to-clear" | "read-write-1-to-clear";
/**
 * Reset value for entire register
 */
export type Resetvalue = number | null;
/**
 * Register description
 */
export type Description2 = string;
/**
 * Bit field name
 */
export type Name3 = string;
/**
 * Starting bit position (LSB = 0)
 */
export type Offset1 = number | null;
/**
 * Number of bits
 */
export type Width = number | null;
/**
 * Bit range string e.g. [7:0]
 */
export type Bits = string | null;
/**
 * Access type
 */
export type AccessType2 = "read-only" | "write-only" | "read-write" | "write-1-to-clear" | "read-write-1-to-clear";
/**
 * Reset/default value
 */
export type Resetvalue1 = number | null;
/**
 * Field description
 */
export type Description3 = string;
/**
 * Enumeration mapping {value: name}
 */
export type Enumeratedvalues = {
  [k: string]: string;
} | null;
/**
 * Bit fields
 */
export type Fields = BitFieldDef[];
/**
 * Child registers (for groups)
 */
export type Registers1 = RegisterDef[];
/**
 * Array replication count
 */
export type Count = number | null;
/**
 * Array replication stride
 */
export type Stride = number | null;
/**
 * Registers in block
 */
export type Registers = RegisterDef[];
/**
 * Address blocks
 */
export type Addressblocks = AddressBlock[];
/**
 * List of memory map definitions (*.mm.yml format)
 */
export type MemoryMapSchema = MemoryMap[];

/**
 * Complete memory map for an IP core (Pydantic model).
 *
 * Organizes registers into address blocks with validation.
 */
export interface MemoryMap {
  name: Name;
  description?: Description;
  addressBlocks?: Addressblocks;
}
/**
 * Contiguous address block within a memory map (Pydantic model).
 *
 * Can contain registers, memory, or reserved space.
 */
export interface AddressBlock {
  name: Name1;
  baseAddress?: Baseaddress;
  range?: Range;
  usage?: BlockUsage;
  access?: AccessType;
  description?: Description1;
  defaultRegWidth?: Defaultregwidth;
  registers?: Registers;
  [k: string]: unknown;
}
/**
 * Register definition within a memory map (Pydantic model for YAML parsing).
 *
 * Represents a memory-mapped register with bit fields.
 */
export interface RegisterDef {
  name: Name2;
  offset?: Offset;
  size?: Size;
  access?: AccessType1;
  resetValue?: Resetvalue;
  description?: Description2;
  fields?: Fields;
  registers?: Registers1;
  count?: Count;
  stride?: Stride;
  [k: string]: unknown;
}
/**
 * Bit field definition within a register (Pydantic model for YAML parsing).
 *
 * Represents a named range of bits with specific access semantics.
 */
export interface BitFieldDef {
  name: Name3;
  offset?: Offset1;
  width?: Width;
  bits?: Bits;
  access?: AccessType2;
  resetValue?: Resetvalue1;
  description?: Description3;
  enumeratedValues?: Enumeratedvalues;
  [k: string]: unknown;
}
