/**
 * This file was automatically generated by scripts/generate-types.js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate-types to regenerate this file.
 */

export type NonEmptyString = string;
export type BusAlias = ShortAlias | VlnvAlias;
export type Scalar = number | string | boolean;
export type DerivedOperation =
  | CopyPortOperation
  | MultiplyPortOperation
  | MultiplyPropertyOperation
  | DividePortOperation
  | DividePropertyOperation
  | DividePortByPropertyOperation
  | MultiplyPropertiesOperation
  | CeilLog2Operation
  | BitsForMaximumOperation
  | MaxEncodableValueOperation;
export type BusConstraint =
  | ConstraintRange
  | ConstraintAllowedValues
  | ConstraintMultipleOf
  | ConstraintPowerOfTwo
  | ConstraintPortWidthsEqual
  | ConstraintPortWidthQuotient
  | ConstraintProductEqualsPort
  | ConstraintPortPresenceRequires
  | ConstraintPropertyRequiredWhenPortPresent
  | ConstraintPropertyFitsPort;
export type ConstraintRange = ConstraintRange1 & {
  ruleId: NonEmptyString;
  code: NonEmptyString;
  kind: 'range';
  port?: NonEmptyString;
  property?: NonEmptyString;
  minimum?: number;
  maximum?: number;
  severity: 'error' | 'warning';
  message?: NonEmptyString;
};
export type ConstraintRange1 = (
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
) &
  (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
  );
export type ConstraintAllowedValues = {
  ruleId: NonEmptyString;
  code: NonEmptyString;
  kind: 'allowedValues';
  port?: NonEmptyString;
  property?: NonEmptyString;
  /**
   * @minItems 1
   */
  values: [Scalar, ...Scalar[]];
  severity: 'error' | 'warning';
  message?: NonEmptyString;
} & ConstraintAllowedValues1;
export type ConstraintAllowedValues1 =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
export type ConstraintMultipleOf = {
  ruleId: NonEmptyString;
  code: NonEmptyString;
  kind: 'multipleOf';
  port?: NonEmptyString;
  property?: NonEmptyString;
  value: number;
  severity: 'error' | 'warning';
  message?: NonEmptyString;
} & ConstraintMultipleOf1;
export type ConstraintMultipleOf1 =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
export type ConstraintPowerOfTwo = {
  ruleId: NonEmptyString;
  code: NonEmptyString;
  kind: 'powerOfTwo';
  port?: NonEmptyString;
  property?: NonEmptyString;
  minimum?: number;
  maximum?: number;
  severity: 'error' | 'warning';
  message?: NonEmptyString;
} & ConstraintPowerOfTwo1;
export type ConstraintPowerOfTwo1 =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };

/**
 * A mapping of bus-definition keys to legacy port declarations and optional versioned conformance contracts.
 */
export interface BusDefinitionFile {
  [k: string]: BusDefinitionEntry;
}
export interface BusDefinitionEntry {
  busType: BusType;
  aliases?: BusAlias[];
  contract?: BusContract;
  /**
   * Artifact provenance assigned by interface scanners. Vivado definitions already exist in the installed catalog; workspace definitions are authored project artifacts.
   */
  source?: 'vivado' | 'workspace';
  ports: BusContractPort[];
}
export interface BusType {
  vendor: NonEmptyString;
  library: NonEmptyString;
  name: NonEmptyString;
  version: NonEmptyString;
  displayName?: NonEmptyString;
  description?: string;
}
export interface ShortAlias {
  kind: 'short';
  value: NonEmptyString;
}
export interface VlnvAlias {
  kind: 'vlnv';
  vendor: NonEmptyString;
  library: NonEmptyString;
  name: NonEmptyString;
  version: NonEmptyString;
}
export interface BusContract {
  version: 1;
  interfaceKind: 'memoryMapped' | 'streaming' | 'conduit';
  modePolicy: ModePolicy;
  interfaceProperties: {
    [k: string]: PropertyDeclaration;
  };
  constraints: BusConstraint[];
}
export interface ModePolicy {
  producer: NonEmptyString;
  consumer: NonEmptyString;
  aliases: {
    [k: string]: NonEmptyString;
  };
}
export interface PropertyDeclaration {
  type: 'integer' | 'boolean' | 'string';
  default?: Scalar;
  minimum?: number;
  maximum?: number;
  /**
   * @minItems 1
   */
  allowedValues?: [Scalar, ...Scalar[]];
  derive?: DerivedOperation;
}
export interface CopyPortOperation {
  operation: 'copyPort';
  port: NonEmptyString;
}
export interface MultiplyPortOperation {
  operation: 'multiplyBy';
  port: NonEmptyString;
  multiplier: number;
}
export interface MultiplyPropertyOperation {
  operation: 'multiplyBy';
  property: NonEmptyString;
  multiplier: number;
}
export interface DividePortOperation {
  operation: 'divideBy';
  port: NonEmptyString;
  divisor: number;
}
export interface DividePropertyOperation {
  operation: 'divideBy';
  property: NonEmptyString;
  divisor: number;
}
export interface DividePortByPropertyOperation {
  operation: 'divideBy';
  port: NonEmptyString;
  divisorProperty: NonEmptyString;
}
export interface MultiplyPropertiesOperation {
  operation: 'multiplyProperties';
  /**
   * @minItems 2
   * @maxItems 2
   */
  properties: [NonEmptyString, NonEmptyString];
}
export interface CeilLog2Operation {
  operation: 'ceilLog2';
  property: NonEmptyString;
}
export interface BitsForMaximumOperation {
  operation: 'bitsForMaximum';
  property: NonEmptyString;
}
export interface MaxEncodableValueOperation {
  operation: 'maxEncodableValue';
  port: NonEmptyString;
}
export interface ConstraintPortWidthsEqual {
  ruleId: NonEmptyString;
  code: NonEmptyString;
  kind: 'portWidthsEqual';
  /**
   * @minItems 2
   */
  ports: [NonEmptyString, NonEmptyString, ...NonEmptyString[]];
  severity: 'error' | 'warning';
  message?: NonEmptyString;
}
export interface ConstraintPortWidthQuotient {
  ruleId: NonEmptyString;
  code: NonEmptyString;
  kind: 'portWidthQuotient';
  port: NonEmptyString;
  dividendPort: NonEmptyString;
  divisor: number;
  severity: 'error' | 'warning';
  message?: NonEmptyString;
}
export interface ConstraintProductEqualsPort {
  ruleId: NonEmptyString;
  code: NonEmptyString;
  kind: 'productEqualsPort';
  port: NonEmptyString;
  /**
   * @minItems 2
   * @maxItems 2
   */
  properties: [NonEmptyString, NonEmptyString];
  severity: 'error' | 'warning';
  message?: NonEmptyString;
}
export interface ConstraintPortPresenceRequires {
  ruleId: NonEmptyString;
  code: NonEmptyString;
  kind: 'portPresenceRequires';
  port: NonEmptyString;
  /**
   * @minItems 1
   */
  requires: [NonEmptyString, ...NonEmptyString[]];
  severity: 'error' | 'warning';
  message?: NonEmptyString;
}
export interface ConstraintPropertyRequiredWhenPortPresent {
  ruleId: NonEmptyString;
  code: NonEmptyString;
  kind: 'propertyRequiredWhenPortPresent';
  port: NonEmptyString;
  property: NonEmptyString;
  severity: 'error' | 'warning';
  message?: NonEmptyString;
}
export interface ConstraintPropertyFitsPort {
  ruleId: NonEmptyString;
  code: NonEmptyString;
  kind: 'propertyFitsPort';
  port: NonEmptyString;
  property: NonEmptyString;
  severity: 'error' | 'warning';
  message?: NonEmptyString;
}
export interface BusContractPort {
  name: NonEmptyString;
  width?: number | NonEmptyString;
  direction?: 'in' | 'out';
  presence?: 'required' | 'optional';
  role?: NonEmptyString;
  polarity?: PortPolarity;
  widthPolicy?: 'root' | 'derived' | 'fixed';
  derivedWidth?: DerivedOperation;
  /**
   * Exact constraint ruleId used when an authored fixed/derived width conflicts with this port's contract width.
   */
  overrideConstraintRuleId?: string;
}
export interface PortPolarity {
  default: 'activeHigh' | 'activeLow';
  roles: {
    activeHigh: NonEmptyString;
    activeLow: NonEmptyString;
  };
}
