/**
 * This file was automatically generated by scripts/generate-types.js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate-types to regenerate this file.
 */

export type StableId = string;

/**
 * Shareable Data Inspector definitions. Transient sample values and capture histories are intentionally excluded.
 */
export interface IPCraftDataInspectorRecipe {
  version: 1;
  name: string;
  description?: string;
  sources: Source[];
  fields: Field[];
  /**
   * @minItems 1
   */
  overlayGroups: [OverlayGroup, ...OverlayGroup[]];
  steps: Step[];
  outputs: Output[];
  view: View;
}
export interface Source {
  id: StableId;
  name: string;
  width: number;
}
export interface Field {
  id: StableId;
  sourceId: StableId;
  name: string;
  msb: number;
  lsb: number;
  groupId: StableId;
  description?: string;
  enumValues?: {
    [k: string]: string;
  };
  importProvenance?: ImportProvenance;
  display: Display;
}
export interface ImportProvenance {
  sourceFile: string;
  registerName: string;
}
export interface Display {
  interpretation: 'hex' | 'binary' | 'unsigned' | 'signed' | 'enum' | 'float' | 'fixedPoint';
  fractionalBits?: number;
  expectedValue?: string;
}
export interface OverlayGroup {
  id: StableId;
  name: string;
}
export interface Step {
  id: StableId;
  type:
    | 'concat'
    | 'slice'
    | 'and'
    | 'or'
    | 'xor'
    | 'not'
    | 'shiftLeft'
    | 'shiftRight'
    | 'zeroExtend'
    | 'signExtend'
    | 'truncate'
    | 'byteSwap';
  inputId: StableId;
  operandId?: StableId;
  msb?: number;
  lsb?: number;
  amount?: number;
  width?: number;
}
export interface Output {
  id: StableId;
  name: string;
  valueId: StableId;
}
export interface View {
  laneWidth: 8 | 16 | 32 | 64;
  zoom: 'overview' | 'field' | 'bit';
  selectedOutputId?: StableId;
  selectedGroupId?: StableId;
}
