import * as path from 'path';

/** Comment text placed in every generated script so IPCraft can recognise its own files. */
export const CLI_SHIM_MARKER = 'Generated by IPCraft';

const isWindows = (platform: NodeJS.Platform): boolean => platform === 'win32';

export function cliScriptName(platform: NodeJS.Platform): string {
  return isWindows(platform) ? 'ipcraft.cmd' : 'ipcraft';
}

function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function cmdEscape(value: string): string {
  return value.replace(/%/g, '%%');
}

function crlf(lines: string[]): string {
  return lines.join('\r\n') + '\r\n';
}

/** Electron < 27 (VS Code < 1.86) requires the run-as-node switch; Electron 27+ and plain Node reject it. */
export function needsRunAsNodeSwitch(electronVersion: string | undefined): boolean {
  return electronVersion !== undefined && parseInt(electronVersion, 10) < 27;
}

/** Script that runs the bundled CLI on VS Code's own runtime (no system Node.js needed). */
export function renderCliLauncher(
  platform: NodeJS.Platform,
  execPath: string,
  cliPath: string,
  runAsNodeSwitch: boolean
): string {
  // Electron < 27 only honours ELECTRON_RUN_AS_NODE together with this switch;
  // newer Electron and plain Node (remote hosts) reject it.
  const sw = runAsNodeSwitch ? ' --ms-enable-electron-run-as-node' : '';
  if (isWindows(platform)) {
    return crlf([
      '@echo off',
      `rem ${CLI_SHIM_MARKER}. Do not edit; regenerated on extension activation.`,
      'setlocal',
      'set ELECTRON_RUN_AS_NODE=1',
      `"${cmdEscape(execPath)}"${sw} "${cmdEscape(cliPath)}" %*`,
      'exit /b %ERRORLEVEL%',
    ]);
  }
  return [
    '#!/bin/sh',
    `# ${CLI_SHIM_MARKER}. Do not edit; regenerated on extension activation.`,
    `ELECTRON_RUN_AS_NODE=1 exec ${shQuote(execPath)}${sw} ${shQuote(cliPath)} "$@"`,
    '',
  ].join('\n');
}

/** External shim that forwards to the launcher inside the extension's global storage. */
export function renderCliShim(platform: NodeJS.Platform, launcherPath: string): string {
  const message = `ipcraft: the IPCraft VS Code extension is not installed or has not started yet (missing ${launcherPath})`;
  if (isWindows(platform)) {
    const cmdMessage = cmdEscape(message).replace(/[()&|<>^]/g, (c) => `^${c}`);
    return crlf([
      '@echo off',
      `rem ${CLI_SHIM_MARKER}. Remove with "IPCraft: Uninstall 'ipcraft' Command from PATH".`,
      `if not exist "${cmdEscape(launcherPath)}" (echo ${cmdMessage} 1>&2& exit /b 127)`,
      `call "${cmdEscape(launcherPath)}" %*`,
      'exit /b %ERRORLEVEL%',
    ]);
  }
  return [
    '#!/bin/sh',
    `# ${CLI_SHIM_MARKER}. Remove with "IPCraft: Uninstall 'ipcraft' Command from PATH".`,
    `[ -x ${shQuote(launcherPath)} ] || { echo ${shQuote(message)} >&2; exit 127; }`,
    `exec ${shQuote(launcherPath)} "$@"`,
    '',
  ].join('\n');
}

export function externalShimDir(
  platform: NodeJS.Platform,
  homeDir: string,
  env: NodeJS.ProcessEnv
): string {
  if (isWindows(platform)) {
    if (!env.LOCALAPPDATA) {
      throw new Error('LOCALAPPDATA is not set; cannot choose a directory for the ipcraft command');
    }
    return path.win32.join(env.LOCALAPPDATA, 'Programs', 'ipcraft');
  }
  return path.posix.join(homeDir, '.local', 'bin');
}

function splitPath(pathValue: string, platform: NodeJS.Platform): string[] {
  return pathValue === '' ? [] : pathValue.split(isWindows(platform) ? ';' : ':');
}

function normalizeEntry(entry: string, platform: NodeJS.Platform): string {
  const trimmed = entry.length > 1 ? entry.replace(/[\\/]+$/, '') : entry;
  return isWindows(platform) ? trimmed.toLowerCase() : trimmed;
}

export function isDirOnPath(pathValue: string, dir: string, platform: NodeJS.Platform): boolean {
  const target = normalizeEntry(dir, platform);
  return splitPath(pathValue, platform).some((e) => normalizeEntry(e, platform) === target);
}

export function addPathEntry(pathValue: string, dir: string, platform: NodeJS.Platform): string {
  if (isDirOnPath(pathValue, dir, platform)) {
    return pathValue;
  }
  const sep = isWindows(platform) ? ';' : ':';
  return pathValue === ''
    ? dir
    : `${pathValue.replace(/[;:]+$/, (m) => (m === sep ? '' : m))}${sep}${dir}`;
}

export function removePathEntry(pathValue: string, dir: string, platform: NodeJS.Platform): string {
  const target = normalizeEntry(dir, platform);
  return splitPath(pathValue, platform)
    .filter((e) => normalizeEntry(e, platform) !== target)
    .join(isWindows(platform) ? ';' : ':');
}
