# regmap_conformance_axil_hw.tcl - Altera Platform Designer Component Definition
# Generated by ipcraft VHDL Generator
#
# Provides component integration for Altera Quartus Platform Designer (Qsys)
# with Avalon-MM slave interface for register access.
#
# Usage: Place this file in the same directory as your RTL files and
# add the directory to Platform Designer's IP search path.

# -----------------------------------------------------------------------------
# Package Definition
# -----------------------------------------------------------------------------
package require qsys

# -----------------------------------------------------------------------------
# Module Properties
# -----------------------------------------------------------------------------
set_module_property DESCRIPTION "Hardware register-conformance test IP, AXI4-Lite variant (cvsoc roadmap, ipcraft-vscode docs/hardware-conformance-test-plan.md, Variant B). Same register map and STIMULUS loopback design as 17_ipcraft_regmap_conformance (Avalon-MM), proving the AXI4-Lite wrapper on real hardware via a JTAG-to-Avalon-MM master and Platform Designer's Avalon<->AXI bridging -- no HPS/Nios II required.
"
set_module_property NAME regmap_conformance_axil
set_module_property VERSION 1.0.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "cvsoc"
set_module_property DISPLAY_NAME "Regmap Conformance Axil"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false

# -----------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Clock Interface
# -----------------------------------------------------------------------------
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1

# -----------------------------------------------------------------------------
# Reset Interface
# -----------------------------------------------------------------------------
add_interface reset_n reset end
set_interface_property reset_n associatedClock clk
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n reset_n reset_n Input 1

# -----------------------------------------------------------------------------
# Bus Interfaces (Generic)
# -----------------------------------------------------------------------------

# Interface: S_AXI_LITE (ipcraft:busif:axi4_lite:1.0)
add_interface S_AXI_LITE axi4lite end
set_interface_property S_AXI_LITE associatedClock clk
set_interface_property S_AXI_LITE associatedReset reset_n
set_interface_property S_AXI_LITE ENABLED true
set_interface_property S_AXI_LITE EXPORT_OF ""
set_interface_property S_AXI_LITE PORT_NAME_MAP ""
set_interface_property S_AXI_LITE CMSIS_SVD_VARIABLES ""
set_interface_property S_AXI_LITE SVD_ADDRESS_GROUP ""

# Type-specific properties

# Ports
add_interface_port S_AXI_LITE s_axil_awaddr awaddr Input 7
add_interface_port S_AXI_LITE s_axil_awvalid awvalid Input 1
add_interface_port S_AXI_LITE s_axil_awready awready Output 1
add_interface_port S_AXI_LITE s_axil_awprot awprot Input 3
add_interface_port S_AXI_LITE s_axil_wdata wdata Input 32
add_interface_port S_AXI_LITE s_axil_wstrb wstrb Input 4
add_interface_port S_AXI_LITE s_axil_wvalid wvalid Input 1
add_interface_port S_AXI_LITE s_axil_wready wready Output 1
add_interface_port S_AXI_LITE s_axil_bresp bresp Output 2
add_interface_port S_AXI_LITE s_axil_bvalid bvalid Output 1
add_interface_port S_AXI_LITE s_axil_bready bready Input 1
add_interface_port S_AXI_LITE s_axil_araddr araddr Input 7
add_interface_port S_AXI_LITE s_axil_arvalid arvalid Input 1
add_interface_port S_AXI_LITE s_axil_arready arready Output 1
add_interface_port S_AXI_LITE s_axil_arprot arprot Input 3
add_interface_port S_AXI_LITE s_axil_rdata rdata Output 32
add_interface_port S_AXI_LITE s_axil_rresp rresp Output 2
add_interface_port S_AXI_LITE s_axil_rvalid rvalid Output 1
add_interface_port S_AXI_LITE s_axil_rready rready Input 1



# -----------------------------------------------------------------------------
# Interrupt Interface(s)
# -----------------------------------------------------------------------------


# -----------------------------------------------------------------------------
# File Sets
# -----------------------------------------------------------------------------
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL regmap_conformance_axil
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file regmap_conformance_axil_pkg.vhd VHDL PATH ../../rtl/regmap_conformance_axil_pkg.vhd
add_fileset_file regmap_conformance_axil_regs.vhd VHDL PATH ../../rtl/regmap_conformance_axil_regs.vhd
add_fileset_file regmap_conformance_axil_core.vhd VHDL PATH ../../rtl/regmap_conformance_axil_core.vhd
add_fileset_file regmap_conformance_axil_axil.vhd VHDL PATH ../../rtl/regmap_conformance_axil_axil.vhd
add_fileset_file regmap_conformance_axil.vhd VHDL PATH ../../rtl/regmap_conformance_axil.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL regmap_conformance_axil
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file regmap_conformance_axil_pkg.vhd VHDL PATH ../../rtl/regmap_conformance_axil_pkg.vhd
add_fileset_file regmap_conformance_axil_regs.vhd VHDL PATH ../../rtl/regmap_conformance_axil_regs.vhd
add_fileset_file regmap_conformance_axil_core.vhd VHDL PATH ../../rtl/regmap_conformance_axil_core.vhd
add_fileset_file regmap_conformance_axil_axil.vhd VHDL PATH ../../rtl/regmap_conformance_axil_axil.vhd
add_fileset_file regmap_conformance_axil.vhd VHDL PATH ../../rtl/regmap_conformance_axil.vhd TOP_LEVEL_FILE
