# Quartus timing constraints for regmap_conformance
# Generated by IPCraft
#
# Each create_clock call defines a clock period derived from the frequency
# specified in the .ip.yml definition.
#
# Adjust the -period values (in nanoseconds) if the target implementation
# frequency differs from the specification.

# Automatically derive PLL clocks to ensure internal system clocks are constrained
derive_pll_clocks -create_base_clocks

# Automatically calculate clock uncertainty (jitter, skew) for accurate STA
derive_clock_uncertainty

# clk — 50MHz
create_clock -period 20.000 -name clk [get_ports { clk }]
