

--------------------------------------------------------------------------------
-- Package: regmap_conformance_axil_pkg
-- Generated by ipcraft VHDL Generator
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package regmap_conformance_axil_pkg is

  ----------------------------------------------------------------------------
  -- Constants
  ----------------------------------------------------------------------------
  constant C_DATA_WIDTH : natural := 32;
  constant C_ADDR_WIDTH : natural := 7;
  constant C_REG_WIDTH  : natural := 4;  -- Bytes per register

  ----------------------------------------------------------------------------
  -- Register Address Map (byte offset, matches the resolved memory map and
  -- the generated component.xml -- never derived from declaration order)
  ----------------------------------------------------------------------------
  constant C_REG_ID_ADDR : natural := 0;  -- addr 00
  constant C_REG_SCRATCH_ADDR : natural := 4;  -- addr 04
  constant C_REG_STIMULUS_ADDR : natural := 8;  -- addr 08
  constant C_REG_STATUS_ADDR : natural := 12;  -- addr 0C
  constant C_REG_INT_STATUS_ADDR : natural := 16;  -- addr 10
  constant C_REG_IRQ_LEGACY_ADDR : natural := 20;  -- addr 14
  constant C_REG_COMMAND_ADDR : natural := 24;  -- addr 18
  constant C_REG_BUSY_ADDR : natural := 28;  -- addr 1C
  constant C_REG_DIAG_ADDR : natural := 32;  -- addr 20
  constant C_REG_WO_MIRROR_ADDR : natural := 36;  -- addr 24
  constant C_REG_LINK_ADDR : natural := 40;  -- addr 28
  constant C_REG_CONTROL_ADDR : natural := 44;  -- addr 2C
  constant C_REG_CHANNEL_0_CONFIG_ADDR : natural := 48;  -- addr 30
  constant C_REG_CHANNEL_0_COUNT_ADDR : natural := 52;  -- addr 34
  constant C_REG_CHANNEL_1_CONFIG_ADDR : natural := 64;  -- addr 40
  constant C_REG_CHANNEL_1_COUNT_ADDR : natural := 68;  -- addr 44

  ----------------------------------------------------------------------------
  -- Register Record Types
  ----------------------------------------------------------------------------

  -- ID register fields
  type t_reg_id is record
    magic : std_logic_vector(31 downto 0);  -- bits 31:0
  end record;

  constant C_REG_ID_RESET : t_reg_id := (
    magic => "11000000111111111110111000000001"
  );

  function to_slv(reg : t_reg_id) return std_logic_vector;
  function to_id(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_id;

  -- SCRATCH register fields
  type t_reg_scratch is record
    value : std_logic_vector(31 downto 0);  -- bits 31:0
  end record;

  constant C_REG_SCRATCH_RESET : t_reg_scratch := (
    value => (others => '0')
  );

  function to_slv(reg : t_reg_scratch) return std_logic_vector;
  function to_scratch(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_scratch;

  -- STIMULUS register fields
  type t_reg_stimulus is record
    status_val : std_logic_vector(3 downto 0);  -- bits 3:0
    sample_evt_trig : std_logic;  -- bit 4
    error_evt_trig : std_logic;  -- bit 5
    legacy_trig : std_logic;  -- bit 6
    cmd_done_trig : std_logic;  -- bit 7
    busy_done_trig : std_logic;  -- bit 8
    link_speed : std_logic_vector(3 downto 0);  -- bits 12:9
  end record;

  constant C_REG_STIMULUS_RESET : t_reg_stimulus := (
    status_val => (others => '0'),
    sample_evt_trig => '0',
    error_evt_trig => '0',
    legacy_trig => '0',
    cmd_done_trig => '0',
    busy_done_trig => '0',
    link_speed => (others => '0')
  );

  function to_slv(reg : t_reg_stimulus) return std_logic_vector;
  function to_stimulus(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_stimulus;

  -- STATUS register fields
  type t_reg_status is record
    value : std_logic_vector(3 downto 0);  -- bits 3:0
  end record;

  constant C_REG_STATUS_RESET : t_reg_status := (
    value => (others => '0')
  );

  function to_slv(reg : t_reg_status) return std_logic_vector;
  function to_status(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_status;

  -- INT_STATUS register fields
  type t_reg_int_status is record
    sample_evt : std_logic;  -- bit 0
    error_evt : std_logic;  -- bit 1
  end record;

  constant C_REG_INT_STATUS_RESET : t_reg_int_status := (
    sample_evt => '0',
    error_evt => '0'
  );

  function to_slv(reg : t_reg_int_status) return std_logic_vector;
  function to_int_status(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_int_status;

  -- IRQ_LEGACY register fields
  type t_reg_irq_legacy is record
    flag : std_logic;  -- bit 0
  end record;

  constant C_REG_IRQ_LEGACY_RESET : t_reg_irq_legacy := (
    flag => '0'
  );

  function to_slv(reg : t_reg_irq_legacy) return std_logic_vector;
  function to_irq_legacy(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_irq_legacy;

  -- COMMAND register fields
  type t_reg_command is record
    start : std_logic;  -- bit 0
  end record;

  constant C_REG_COMMAND_RESET : t_reg_command := (
    start => '0'
  );

  function to_slv(reg : t_reg_command) return std_logic_vector;
  function to_command(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_command;

  -- BUSY register fields
  type t_reg_busy is record
    active : std_logic;  -- bit 0
  end record;

  constant C_REG_BUSY_RESET : t_reg_busy := (
    active => '0'
  );

  function to_slv(reg : t_reg_busy) return std_logic_vector;
  function to_busy(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_busy;

  -- DIAG register fields
  type t_reg_diag is record
    scratch : std_logic_vector(7 downto 0);  -- bits 7:0
  end record;

  constant C_REG_DIAG_RESET : t_reg_diag := (
    scratch => (others => '0')
  );

  function to_slv(reg : t_reg_diag) return std_logic_vector;
  function to_diag(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_diag;

  -- WO_MIRROR register fields
  type t_reg_wo_mirror is record
    scratch : std_logic_vector(7 downto 0);  -- bits 7:0
  end record;

  constant C_REG_WO_MIRROR_RESET : t_reg_wo_mirror := (
    scratch => (others => '0')
  );

  function to_slv(reg : t_reg_wo_mirror) return std_logic_vector;
  function to_wo_mirror(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_wo_mirror;

  -- LINK register fields
  type t_reg_link is record
    speed : std_logic_vector(3 downto 0);  -- bits 3:0
    speed_changed : std_logic;  -- bit 8
  end record;

  constant C_REG_LINK_RESET : t_reg_link := (
    speed => (others => '0'),
    speed_changed => '0'
  );

  function to_slv(reg : t_reg_link) return std_logic_vector;
  function to_link(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_link;

  -- CONTROL register fields
  type t_reg_control is record
    mode : std_logic_vector(1 downto 0);  -- bits 1:0
  end record;

  constant C_REG_CONTROL_RESET : t_reg_control := (
    mode => "01"
  );

  function to_slv(reg : t_reg_control) return std_logic_vector;
  function to_control(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_control;

  -- CHANNEL_0_CONFIG register fields
  type t_reg_channel_0_config is record
    value : std_logic_vector(7 downto 0);  -- bits 7:0
  end record;

  constant C_REG_CHANNEL_0_CONFIG_RESET : t_reg_channel_0_config := (
    value => (others => '0')
  );

  function to_slv(reg : t_reg_channel_0_config) return std_logic_vector;
  function to_channel_0_config(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_channel_0_config;

  -- CHANNEL_0_COUNT register fields
  type t_reg_channel_0_count is record
    samples : std_logic_vector(7 downto 0);  -- bits 7:0
  end record;

  constant C_REG_CHANNEL_0_COUNT_RESET : t_reg_channel_0_count := (
    samples => (others => '0')
  );

  function to_slv(reg : t_reg_channel_0_count) return std_logic_vector;
  function to_channel_0_count(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_channel_0_count;

  -- CHANNEL_1_CONFIG register fields
  type t_reg_channel_1_config is record
    value : std_logic_vector(7 downto 0);  -- bits 7:0
  end record;

  constant C_REG_CHANNEL_1_CONFIG_RESET : t_reg_channel_1_config := (
    value => (others => '0')
  );

  function to_slv(reg : t_reg_channel_1_config) return std_logic_vector;
  function to_channel_1_config(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_channel_1_config;

  -- CHANNEL_1_COUNT register fields
  type t_reg_channel_1_count is record
    samples : std_logic_vector(7 downto 0);  -- bits 7:0
  end record;

  constant C_REG_CHANNEL_1_COUNT_RESET : t_reg_channel_1_count := (
    samples => (others => '0')
  );

  function to_slv(reg : t_reg_channel_1_count) return std_logic_vector;
  function to_channel_1_count(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_channel_1_count;

  -- W1C event-pulse record types (hardware drives a 1-cycle strobe to set a sticky bit)

  type t_reg_int_status_pulse is record
    sample_evt_pulse : std_logic;  -- event strobe → sets INT_STATUS.sample_evt
    error_evt_pulse : std_logic;  -- event strobe → sets INT_STATUS.error_evt
  end record;

  constant C_REG_INT_STATUS_PULSE_RESET : t_reg_int_status_pulse := (
    sample_evt_pulse => '0',
    error_evt_pulse => '0'
  );

  type t_reg_irq_legacy_pulse is record
    flag_pulse : std_logic;  -- event strobe → sets IRQ_LEGACY.flag
  end record;

  constant C_REG_IRQ_LEGACY_PULSE_RESET : t_reg_irq_legacy_pulse := (
    flag_pulse => '0'
  );

  -- SC event-clear record types (hardware drives a 1-cycle strobe to clear a sticky bit)

  type t_reg_command_clear is record
    start_clear : std_logic;  -- event strobe → clears COMMAND.start
  end record;

  constant C_REG_COMMAND_CLEAR_RESET : t_reg_command_clear := (
    start_clear => '0'
  );

  type t_reg_busy_clear is record
    active_clear : std_logic;  -- event strobe → clears BUSY.active
  end record;

  constant C_REG_BUSY_CLEAR_RESET : t_reg_busy_clear := (
    active_clear => '0'
  );

  -- Hardware-driven value-port record types: live values for read-only fields
  -- mixed into an otherwise SW-writable register (includes CoS-monitored
  -- fields, which are always mixed by construction).

  type t_reg_link_val is record
    speed : std_logic_vector(3 downto 0);  -- hardware-driven, read-only in LINK
  end record;

  constant C_REG_LINK_VAL_RESET : t_reg_link_val := (
    speed => (others => '0')
  );

  ----------------------------------------------------------------------------
  -- Aggregate Register Records (for clean port interface)
  ----------------------------------------------------------------------------

  -- SW -> HW: Registers written by software, read by hardware
  type t_regs_sw2hw is record
    scratch : t_reg_scratch;
    stimulus : t_reg_stimulus;
    int_status : t_reg_int_status;
    irq_legacy : t_reg_irq_legacy;
    command : t_reg_command;
    busy : t_reg_busy;
    diag : t_reg_diag;
    link : t_reg_link;
    control : t_reg_control;
    channel_0_config : t_reg_channel_0_config;
    channel_1_config : t_reg_channel_1_config;
  end record;

  constant C_REGS_SW2HW_RESET : t_regs_sw2hw := (
    scratch => C_REG_SCRATCH_RESET,
    stimulus => C_REG_STIMULUS_RESET,
    int_status => C_REG_INT_STATUS_RESET,
    irq_legacy => C_REG_IRQ_LEGACY_RESET,
    command => C_REG_COMMAND_RESET,
    busy => C_REG_BUSY_RESET,
    diag => C_REG_DIAG_RESET,
    link => C_REG_LINK_RESET,
    control => C_REG_CONTROL_RESET,
    channel_0_config => C_REG_CHANNEL_0_CONFIG_RESET,
    channel_1_config => C_REG_CHANNEL_1_CONFIG_RESET
  );

  -- HW -> SW: Status registers (RO) + W1C/SC event pulses + hardware-driven value ports
  type t_regs_hw2sw is record
    id : t_reg_id;
    status : t_reg_status;
    wo_mirror : t_reg_wo_mirror;
    channel_0_count : t_reg_channel_0_count;
    channel_1_count : t_reg_channel_1_count;
    int_status_pulse : t_reg_int_status_pulse;  -- W1C event pulses for INT_STATUS
    irq_legacy_pulse : t_reg_irq_legacy_pulse;  -- W1C event pulses for IRQ_LEGACY
    command_clear : t_reg_command_clear;  -- SC event clear pulses for COMMAND
    busy_clear : t_reg_busy_clear;  -- SC event clear pulses for BUSY
    link_val : t_reg_link_val;  -- hardware-driven values for LINK
  end record;

  constant C_REGS_HW2SW_RESET : t_regs_hw2sw := (
    id => C_REG_ID_RESET,
    status => C_REG_STATUS_RESET,
    wo_mirror => C_REG_WO_MIRROR_RESET,
    channel_0_count => C_REG_CHANNEL_0_COUNT_RESET,
    channel_1_count => C_REG_CHANNEL_1_COUNT_RESET,
    int_status_pulse => C_REG_INT_STATUS_PULSE_RESET,
    irq_legacy_pulse => C_REG_IRQ_LEGACY_PULSE_RESET,
    command_clear => C_REG_COMMAND_CLEAR_RESET,
    busy_clear => C_REG_BUSY_CLEAR_RESET,
    link_val => C_REG_LINK_VAL_RESET
  );

end package regmap_conformance_axil_pkg;


package body regmap_conformance_axil_pkg is

  ----------------------------------------------------------------------------
  -- Conversion Functions
  ----------------------------------------------------------------------------

  -- ID conversions
  function to_slv(reg : t_reg_id) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(31 downto 0) := reg.magic;
    return slv;
  end function;

  function to_id(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_id is
    variable reg : t_reg_id;
  begin
    reg.magic := slv(31 downto 0);
    return reg;
  end function;

  -- SCRATCH conversions
  function to_slv(reg : t_reg_scratch) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(31 downto 0) := reg.value;
    return slv;
  end function;

  function to_scratch(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_scratch is
    variable reg : t_reg_scratch;
  begin
    reg.value := slv(31 downto 0);
    return reg;
  end function;

  -- STIMULUS conversions
  function to_slv(reg : t_reg_stimulus) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(3 downto 0) := reg.status_val;
    slv(4) := reg.sample_evt_trig;
    slv(5) := reg.error_evt_trig;
    slv(6) := reg.legacy_trig;
    slv(7) := reg.cmd_done_trig;
    slv(8) := reg.busy_done_trig;
    slv(12 downto 9) := reg.link_speed;
    return slv;
  end function;

  function to_stimulus(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_stimulus is
    variable reg : t_reg_stimulus;
  begin
    reg.status_val := slv(3 downto 0);
    reg.sample_evt_trig := slv(4);
    reg.error_evt_trig := slv(5);
    reg.legacy_trig := slv(6);
    reg.cmd_done_trig := slv(7);
    reg.busy_done_trig := slv(8);
    reg.link_speed := slv(12 downto 9);
    return reg;
  end function;

  -- STATUS conversions
  function to_slv(reg : t_reg_status) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(3 downto 0) := reg.value;
    return slv;
  end function;

  function to_status(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_status is
    variable reg : t_reg_status;
  begin
    reg.value := slv(3 downto 0);
    return reg;
  end function;

  -- INT_STATUS conversions
  function to_slv(reg : t_reg_int_status) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(0) := reg.sample_evt;
    slv(1) := reg.error_evt;
    return slv;
  end function;

  function to_int_status(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_int_status is
    variable reg : t_reg_int_status;
  begin
    reg.sample_evt := slv(0);
    reg.error_evt := slv(1);
    return reg;
  end function;

  -- IRQ_LEGACY conversions
  function to_slv(reg : t_reg_irq_legacy) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(0) := reg.flag;
    return slv;
  end function;

  function to_irq_legacy(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_irq_legacy is
    variable reg : t_reg_irq_legacy;
  begin
    reg.flag := slv(0);
    return reg;
  end function;

  -- COMMAND conversions
  function to_slv(reg : t_reg_command) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(0) := reg.start;
    return slv;
  end function;

  function to_command(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_command is
    variable reg : t_reg_command;
  begin
    reg.start := slv(0);
    return reg;
  end function;

  -- BUSY conversions
  function to_slv(reg : t_reg_busy) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(0) := reg.active;
    return slv;
  end function;

  function to_busy(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_busy is
    variable reg : t_reg_busy;
  begin
    reg.active := slv(0);
    return reg;
  end function;

  -- DIAG conversions
  function to_slv(reg : t_reg_diag) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(7 downto 0) := reg.scratch;
    return slv;
  end function;

  function to_diag(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_diag is
    variable reg : t_reg_diag;
  begin
    reg.scratch := slv(7 downto 0);
    return reg;
  end function;

  -- WO_MIRROR conversions
  function to_slv(reg : t_reg_wo_mirror) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(7 downto 0) := reg.scratch;
    return slv;
  end function;

  function to_wo_mirror(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_wo_mirror is
    variable reg : t_reg_wo_mirror;
  begin
    reg.scratch := slv(7 downto 0);
    return reg;
  end function;

  -- LINK conversions
  function to_slv(reg : t_reg_link) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(3 downto 0) := reg.speed;
    slv(8) := reg.speed_changed;
    return slv;
  end function;

  function to_link(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_link is
    variable reg : t_reg_link;
  begin
    reg.speed := slv(3 downto 0);
    reg.speed_changed := slv(8);
    return reg;
  end function;

  -- CONTROL conversions
  function to_slv(reg : t_reg_control) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(1 downto 0) := reg.mode;
    return slv;
  end function;

  function to_control(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_control is
    variable reg : t_reg_control;
  begin
    reg.mode := slv(1 downto 0);
    return reg;
  end function;

  -- CHANNEL_0_CONFIG conversions
  function to_slv(reg : t_reg_channel_0_config) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(7 downto 0) := reg.value;
    return slv;
  end function;

  function to_channel_0_config(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_channel_0_config is
    variable reg : t_reg_channel_0_config;
  begin
    reg.value := slv(7 downto 0);
    return reg;
  end function;

  -- CHANNEL_0_COUNT conversions
  function to_slv(reg : t_reg_channel_0_count) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(7 downto 0) := reg.samples;
    return slv;
  end function;

  function to_channel_0_count(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_channel_0_count is
    variable reg : t_reg_channel_0_count;
  begin
    reg.samples := slv(7 downto 0);
    return reg;
  end function;

  -- CHANNEL_1_CONFIG conversions
  function to_slv(reg : t_reg_channel_1_config) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(7 downto 0) := reg.value;
    return slv;
  end function;

  function to_channel_1_config(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_channel_1_config is
    variable reg : t_reg_channel_1_config;
  begin
    reg.value := slv(7 downto 0);
    return reg;
  end function;

  -- CHANNEL_1_COUNT conversions
  function to_slv(reg : t_reg_channel_1_count) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(7 downto 0) := reg.samples;
    return slv;
  end function;

  function to_channel_1_count(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_channel_1_count is
    variable reg : t_reg_channel_1_count;
  begin
    reg.samples := slv(7 downto 0);
    return reg;
  end function;

end package body regmap_conformance_axil_pkg;
