


--------------------------------------------------------------------------------
-- Entity: regmap_conformance_axil_axil
-- Description: AXI-Lite slave interface for register access
-- Generated by ipcraft VHDL Generator
--
-- Register Map:
--   0000 : ID (read-only)
--   0004 : SCRATCH (read-write)
--   0008 : STIMULUS (read-write)
--   000C : STATUS (read-only)
--   0010 : INT_STATUS (read-write)
--   0014 : IRQ_LEGACY (write-only)
--   0018 : COMMAND (write-self-clearing)
--   001C : BUSY (read-write-self-clearing)
--   0020 : DIAG (write-only)
--   0024 : WO_MIRROR (read-only)
--   0028 : LINK (read-write)
--   002C : CONTROL (read-write)
--   0030 : CHANNEL_0_CONFIG (read-write)
--   0034 : CHANNEL_0_COUNT (read-only)
--   0040 : CHANNEL_1_CONFIG (read-write)
--   0044 : CHANNEL_1_COUNT (read-only)
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.regmap_conformance_axil_pkg.all;
entity regmap_conformance_axil_axil is
  port (
    -- Clock and reset
    clk : in std_logic;
    rst : in std_logic;

    -- AXI-Lite Slave Interface
    s_axil_awaddr  : in  std_logic_vector(6 downto 0);
    s_axil_awvalid : in  std_logic;
    s_axil_awready : out std_logic;
    s_axil_awprot  : in  std_logic_vector(2 downto 0);
    s_axil_wdata   : in  std_logic_vector(31 downto 0);
    s_axil_wstrb   : in  std_logic_vector(3 downto 0);
    s_axil_wvalid  : in  std_logic;
    s_axil_wready  : out std_logic;
    s_axil_bresp   : out std_logic_vector(1 downto 0);
    s_axil_bvalid  : out std_logic;
    s_axil_bready  : in  std_logic;
    s_axil_araddr  : in  std_logic_vector(6 downto 0);
    s_axil_arvalid : in  std_logic;
    s_axil_arready : out std_logic;
    s_axil_arprot  : in  std_logic_vector(2 downto 0);
    s_axil_rdata   : out std_logic_vector(31 downto 0);
    s_axil_rresp   : out std_logic_vector(1 downto 0);
    s_axil_rvalid  : out std_logic;
    s_axil_rready  : in  std_logic;
    -- Register interface
    regs_out : out t_regs_sw2hw;  -- To core (SW-writable)
    regs_in  : in  t_regs_hw2sw   -- From core (HW-writable / W1C pulses / CoS values)
  );
end entity regmap_conformance_axil_axil;

architecture rtl of regmap_conformance_axil_axil is

  -- AXI-Lite response constants
  constant C_RESP_OKAY   : std_logic_vector(1 downto 0) := "00";
  constant C_RESP_SLVERR : std_logic_vector(1 downto 0) := "10";

  -- AXI internal signals (output registers + address latches only; input ports used directly)
  signal awaddr   : std_logic_vector(6 downto 0)                     := (others => '0');
  signal awready  : std_logic                                        := '0';
  signal wready   : std_logic                                        := '0';
  signal bresp    : std_logic_vector(1 downto 0)                     := C_RESP_OKAY;
  signal bvalid   : std_logic                                        := '0';
  signal araddr   : std_logic_vector(6 downto 0)                     := (others => '0');
  signal arready  : std_logic                                        := '0';
  signal rdata    : std_logic_vector(31 downto 0)                    := (others => '0');
  signal rresp    : std_logic_vector(1 downto 0)                     := C_RESP_OKAY;
  signal rvalid   : std_logic                                        := '0';

  -- Register bank interface signals
  signal wr_en     : std_logic;
  signal wr_addr   : std_logic_vector(C_ADDR_WIDTH-1 downto 0);
  signal wr_data   : std_logic_vector(C_DATA_WIDTH-1 downto 0);
  signal wr_strb   : std_logic_vector((C_DATA_WIDTH/8)-1 downto 0);
  signal rd_en     : std_logic;
  signal rd_addr   : std_logic_vector(C_ADDR_WIDTH-1 downto 0);
  signal rd_data   : std_logic_vector(C_DATA_WIDTH-1 downto 0);
  signal rd_valid  : std_logic;

  -- Write data/strobe latches: hold W-channel data until the register write
  -- fires so the master is free to de-assert WVALID after the W handshake.
  signal wdata_latch  : std_logic_vector(C_DATA_WIDTH-1 downto 0)    := (others => '0');
  signal wstrb_latch  : std_logic_vector((C_DATA_WIDTH/8)-1 downto 0) := (others => '0');
  -- Gate wr_en to a single-cycle pulse: wr_pending tracks that wr_en has
  -- already fired this transaction so the second combinatorial cycle is blocked.
  signal wr_pending   : std_logic := '0';
  -- Registered flag for an unmapped read address: lets read_valid_proc respond
  -- with SLVERR one cycle after rd_en, matching the timing of rd_valid.
  signal rd_invalid_d : std_logic := '0';

  -- Write transaction tracking using VHDL 2008 records
  type t_write_transaction is record
    aw_en         : std_logic; -- Address write enable flag
    addr_received : std_logic; -- Address has been received
    data_received : std_logic; -- Data has been received
  end record t_write_transaction;

  signal write_txn : t_write_transaction := ('1', '0', '0');

begin

  ----------------------------------------------------------------------------
  -- Register Bank Instantiation
  ----------------------------------------------------------------------------
  u_regs : entity work.regmap_conformance_axil_regs
    port map (
      clk      => clk,
      rst      => rst,
      wr_en    => wr_en,
      wr_addr  => wr_addr,
      wr_data  => wr_data,
      wr_strb  => wr_strb,
      rd_en    => rd_en,
      rd_addr  => rd_addr,
      rd_data  => rd_data,
      rd_valid => rd_valid,
      regs_out => regs_out,
      regs_in  => regs_in
    );

  -- Connect internal output registers to AXI-Lite ports
  s_axil_awready <= awready;
  s_axil_wready <= wready;
  s_axil_bresp <= bresp;
  s_axil_bvalid <= bvalid;
  s_axil_arready <= arready;
  s_axil_rdata <= rdata;
  s_axil_rresp <= rresp;
  s_axil_rvalid <= rvalid;

  ----------------------------------------------------------------------------
  -- Write Address Channel
  -- Accept write address when AWVALID is asserted (independent of WVALID)
  ----------------------------------------------------------------------------
  write_addr_proc : process (clk) is
  begin
    if rising_edge(clk) then
      if rst = '1' then
        awready             <= '0';
        write_txn.aw_en     <= '1';
        awaddr              <= (others => '0');
        write_txn.addr_received <= '0';
      else
        if (awready = '0' and s_axil_awvalid = '1' and write_txn.aw_en = '1') then
          -- Ready to accept write address; latch address from port
          awready             <= '1';
          write_txn.aw_en     <= '0';
          awaddr              <= s_axil_awaddr;
          write_txn.addr_received <= '1';
        elsif (bvalid = '1' and s_axil_bready = '1') then
          -- Write response completed, ready for next transaction
          write_txn.aw_en         <= '1';
          write_txn.addr_received <= '0';
          awready             <= '0';
        else
          awready <= '0';
        end if;
      end if;
    end if;
  end process write_addr_proc;

  ----------------------------------------------------------------------------
  -- Write Data Channel
  -- Accept write data when WVALID is asserted (independent of AWVALID)
  ----------------------------------------------------------------------------
  write_data_proc : process (clk) is
  begin
    if rising_edge(clk) then
      if rst = '1' then
        wready              <= '0';
        write_txn.data_received <= '0';
      else
        if (wready = '0' and s_axil_wvalid = '1') then
          -- Ready to accept write data; latch data and strobe immediately
          wready              <= '1';
          write_txn.data_received <= '1';
          wdata_latch         <= s_axil_wdata;
          wstrb_latch         <= s_axil_wstrb;
        elsif (bvalid = '1' and s_axil_bready = '1') then
          -- Write response completed, ready for next transaction
          write_txn.data_received <= '0';
          wready              <= '0';
        else
          wready <= '0';
        end if;
      end if;
    end if;
  end process write_data_proc;

  ----------------------------------------------------------------------------
  -- Write Enable Pulse Gate
  -- wr_pending shadows the combinatorial wr_en one cycle later, ensuring
  -- wr_en is a single-cycle pulse even when addr/data_received stay high
  -- until the B-channel handshake.
  ----------------------------------------------------------------------------
  wr_pending_proc : process (clk) is
  begin
    if rising_edge(clk) then
      if rst = '1' then
        wr_pending <= '0';
      else
        wr_pending <= write_txn.addr_received and write_txn.data_received;
      end if;
    end if;
  end process wr_pending_proc;

  ----------------------------------------------------------------------------
  -- Register Write Control
  -- Generate write enable to register bank when both address and data received
  ----------------------------------------------------------------------------
  wr_en   <= write_txn.addr_received and write_txn.data_received and not wr_pending;
  wr_addr <= awaddr(C_ADDR_WIDTH-1 downto 0);
  wr_data <= wdata_latch;
  wr_strb <= wstrb_latch;

  ----------------------------------------------------------------------------
  -- Write Response Logic
  ----------------------------------------------------------------------------
  write_response_proc : process (clk) is
  begin
    if rising_edge(clk) then
      if rst = '1' then
        bvalid <= '0';
        bresp  <= C_RESP_OKAY;
      else
        if (write_txn.addr_received = '1' and write_txn.data_received = '1' and bvalid = '0') then
          -- Both address and data received, assert write response
          bvalid <= '1';
          if to_integer(unsigned(awaddr(C_ADDR_WIDTH-1 downto 0))) < 72 then
            bresp <= C_RESP_OKAY;
          else
            bresp <= C_RESP_SLVERR;
          end if;
        elsif (s_axil_bready = '1' and bvalid = '1') then
          -- Write response accepted by master
          bvalid <= '0';
        end if;
      end if;
    end if;
  end process write_response_proc;

  ----------------------------------------------------------------------------
  -- Read Address Channel
  ----------------------------------------------------------------------------
  read_addr_proc : process (clk) is
  begin
    if rising_edge(clk) then
      if rst = '1' then
        arready <= '0';
        araddr  <= (others => '0');
      else
        if (arready = '0' and s_axil_arvalid = '1') then
          arready <= '1';
          araddr  <= s_axil_araddr;  -- latch address from port
        else
          arready <= '0';
        end if;
      end if;
    end if;
  end process read_addr_proc;

  ----------------------------------------------------------------------------
  -- Register Read Control
  -- Trigger read from register bank when address is accepted
  ----------------------------------------------------------------------------
  rd_en   <= arready and s_axil_arvalid and not rvalid;
  rd_addr <= araddr(C_ADDR_WIDTH-1 downto 0);

  ----------------------------------------------------------------------------
  -- Invalid Read Address Detection
  -- The register bank asserts rd_valid on every rd_en, mapped or not, so
  -- read_valid_proc must check rd_invalid_d ahead of rd_valid to return
  -- SLVERR for unmapped addresses.
  ----------------------------------------------------------------------------
  rd_invalid_proc : process (clk) is
  begin
    if rising_edge(clk) then
      if rst = '1' then
        rd_invalid_d <= '0';
      else
        if rd_en = '1' and to_integer(unsigned(rd_addr(C_ADDR_WIDTH-1 downto 0))) >= 72 then
          rd_invalid_d <= '1';
        else
          rd_invalid_d <= '0';
        end if;
      end if;
    end if;
  end process rd_invalid_proc;

  ----------------------------------------------------------------------------
  -- Read Valid Generation
  -- Assert RVALID when register bank provides valid read data or when the
  -- address was unmapped (SLVERR, zero data). rd_invalid_d is checked first
  -- because rd_valid is asserted by the register bank for every rd_en,
  -- mapped or not.
  ----------------------------------------------------------------------------
  read_valid_proc : process (clk) is
  begin
    if rising_edge(clk) then
      if rst = '1' then
        rvalid <= '0';
        rresp  <= C_RESP_OKAY;
        rdata  <= (others => '0');
      else
        if rd_invalid_d = '1' then
          -- Unmapped read address: complete transaction with SLVERR and zero data
          rvalid <= '1';
          rresp  <= C_RESP_SLVERR;
          rdata  <= (others => '0');
        elsif rd_valid = '1' then
          -- Register bank has valid data
          rvalid <= '1';
          rresp  <= C_RESP_OKAY;
          rdata  <= rd_data;
        elsif (rvalid = '1' and s_axil_rready = '1') then
          -- Master accepted read data
          rvalid <= '0';
        end if;
      end if;
    end if;
  end process read_valid_proc;

end architecture rtl;

