

--------------------------------------------------------------------------------
-- Entity: regmap_conformance_axil
-- Description: Hardware register-conformance test IP, AXI4-Lite variant (cvsoc roadmap, ipcraft-vscode docs/hardware-conformance-test-plan.md, Variant B). Same register map and STIMULUS loopback design as 17_ipcraft_regmap_conformance (Avalon-MM), proving the AXI4-Lite wrapper on real hardware via a JTAG-to-Avalon-MM master and Platform Designer's Avalon<->AXI bridging -- no HPS/Nios II required.

-- Generated by ipcraft VHDL Generator
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.regmap_conformance_axil_pkg.all;

entity regmap_conformance_axil is
  port (
    -- Clock and reset
    clk : in std_logic;
    reset_n : in std_logic;


    -- S_AXI_LITE (SLAVE)
    s_axil_awaddr  : in  std_logic_vector(6 downto 0);
    s_axil_awvalid : in  std_logic;
    s_axil_awready : out std_logic;
    s_axil_awprot  : in  std_logic_vector(2 downto 0);
    s_axil_wdata   : in  std_logic_vector(31 downto 0);
    s_axil_wstrb   : in  std_logic_vector(3 downto 0);
    s_axil_wvalid  : in  std_logic;
    s_axil_wready  : out std_logic;
    s_axil_bresp   : out std_logic_vector(1 downto 0);
    s_axil_bvalid  : out std_logic;
    s_axil_bready  : in  std_logic;
    s_axil_araddr  : in  std_logic_vector(6 downto 0);
    s_axil_arvalid : in  std_logic;
    s_axil_arready : out std_logic;
    s_axil_arprot  : in  std_logic_vector(2 downto 0);
    s_axil_rdata   : out std_logic_vector(31 downto 0);
    s_axil_rresp   : out std_logic_vector(1 downto 0);
    s_axil_rvalid  : out std_logic;
    s_axil_rready  : in  std_logic
    );
end entity regmap_conformance_axil;

architecture rtl of regmap_conformance_axil is

    -- Internal register signals
  signal regs_sw2hw : t_regs_sw2hw;
  signal regs_hw2sw : t_regs_hw2sw;

begin


    ----------------------------------------------------------------------------
    -- Bus Wrapper Instance
    ----------------------------------------------------------------------------
    u_axil : entity work.regmap_conformance_axil_axil
    port map (
      clk => clk,
      rst => not reset_n,

      s_axil_awaddr  => s_axil_awaddr,
      s_axil_awvalid => s_axil_awvalid,
      s_axil_awready => s_axil_awready,
      s_axil_awprot  => s_axil_awprot,
      s_axil_wdata   => s_axil_wdata,
      s_axil_wstrb   => s_axil_wstrb,
      s_axil_wvalid  => s_axil_wvalid,
      s_axil_wready  => s_axil_wready,
      s_axil_bresp   => s_axil_bresp,
      s_axil_bvalid  => s_axil_bvalid,
      s_axil_bready  => s_axil_bready,
      s_axil_araddr  => s_axil_araddr,
      s_axil_arvalid => s_axil_arvalid,
      s_axil_arready => s_axil_arready,
      s_axil_arprot  => s_axil_arprot,
      s_axil_rdata   => s_axil_rdata,
      s_axil_rresp   => s_axil_rresp,
      s_axil_rvalid  => s_axil_rvalid,
      s_axil_rready  => s_axil_rready,
      regs_out => regs_sw2hw,
      regs_in  => regs_hw2sw
    );

    ----------------------------------------------------------------------------
    -- Core Logic Instance
    ----------------------------------------------------------------------------
    u_core : entity work.regmap_conformance_axil_core
    port map (
      clk => clk,
      rst => not reset_n,
      regs_in  => regs_sw2hw,
      regs_out => regs_hw2sw
    );

end architecture rtl;
