/**
 * This file was automatically generated by scripts/generate-types.js.
 * DO NOT MODIFY IT BY HAND. Instead, modify template_context.schema.json,
 * and run npm run generate-types to regenerate this file.
 */

/**
 * Versioned template context passed to all Nunjucks/Jinja2 templates during IP core generation. This is the public API for third-party scaffold packs.
 */
export interface TemplateContext {
  /**
   * Semantic version of the template context contract.
   */
  contract_version: '1.0.0';
  name: string;
  entity_name: string;
  has_memory_mapped_slave: boolean;
  data_width: number;
  addr_width: number;
  reg_width: number;
  registers: AnnotatedRegister[];
  sw_registers: Register[];
  hw_registers: Register[];
  w1c_registers: W1CRegister[];
  sc_registers: Register[];
  cos_registers: CosRegister[];
  generics: Generic[];
  xgui_pages: XguiPage[];
  user_ports: UserPort[];
  interrupt_ports: InterruptPort[];
  bus_type: string;
  bus_prefix: string;
  bus_ports: BusPort[];
  secondary_bus_ports: BusPort[];
  secondary_bus_interfaces: SecondaryBusInterface[];
  expanded_bus_interfaces: ExpandedBusInterface[];
  elaborate_port_widths: ElaboratePortWidth[];
  memory_maps: MemoryMap[];
  clock_port: string;
  reset_port: string;
  reset_active_high: boolean;
  clocks_with_period: ClockWithPeriod[];
  memmap_relpath: string;
  /**
   * True when any parameterized port width uses a VHDL math_real function (clog2/log2/ceil/floor), so the entity context clause must add `use ieee.math_real.all;`.
   */
  uses_math_real?: boolean;
  vendor?: string;
  library?: string;
  version?: string;
  author?: string;
  description: string;
  display_name: string;
}
export interface AnnotatedRegister {
  name: string;
  offset: number;
  access: string;
  description: string;
  fields: Field[];
  has_cos_fields: boolean;
}
export interface Field {
  name: string;
  offset: number;
  width: number;
  access: string;
  reset_value: number | null;
  description: string;
  monitorChangeOf: string | null;
}
export interface Register {
  name: string;
  offset: number;
  access: string;
  description: string;
  fields: Field[];
}
export interface W1CRegister {
  name: string;
  offset: number;
  access: string;
  description: string;
  fields: W1CField[];
}
export interface W1CField {
  name: string;
  offset: number;
  width: number;
  access: string;
  reset_value: number | null;
  description: string;
  monitorChangeOf: string | null;
  is_cos: boolean;
}
export interface CosRegister {
  name: string;
  offset: number;
  access: string;
  description: string;
  fields: Field[];
  cos_fields: CosField[];
  val_fields: Field[];
}
export interface CosField {
  name: string;
  offset: number;
  width: number;
  access: string;
  reset_value: number | null;
  description: string;
  monitorChangeOf: string | null;
  monitored_field: Field;
}
export interface Generic {
  name: string;
  type: string;
  sv_type: string;
  default_value: number | number | string | boolean | null;
  sv_default: number | number | string | boolean | null;
  description: string;
  min: number | null;
  max: number | null;
  allowed_values: (number | string)[] | null;
  ui_page: string;
  ui_group: string;
}
export interface XguiPage {
  name: string;
  tcl_var: string;
  groups: XguiGroup[];
  ungrouped_params: {
    name: string;
    tooltip: string;
  }[];
}
export interface XguiGroup {
  name: string;
  tcl_var: string;
  params: {
    name: string;
    tooltip: string;
  }[];
}
export interface UserPort {
  name: string;
  direction: string;
  sv_direction: string;
  type: string;
  sv_type: string;
  width: number;
  width_expr: string | null;
  is_parameterized: boolean;
  default_width: number | null;
  tcl_width?: string;
}
export interface InterruptPort {
  name: string;
  direction: string;
  sensitivity: string;
}
export interface BusPort {
  logical_name: string;
  name: string;
  direction: string;
  sv_direction: string;
  width: number;
  width_expr: string | null;
  is_parameterized: boolean;
  default_width: number | null;
  type: string;
  sv_type: string;
  tcl_width?: string;
}
export interface SecondaryBusInterface {
  name: string;
  mode: string;
  ports: BusPort[];
}
export interface ExpandedBusInterface {
  name?: string;
  type?: string;
  mode: string;
  physicalPrefix: string;
  useOptionalPorts: string[];
  portWidthOverrides: {
    [k: string]: number | string;
  };
  portNameOverrides?: {
    [k: string]: string;
  };
  absentPorts?: string[];
  associatedClock?: string;
  associatedReset?: string;
  conduitPorts?: ConduitPort[];
  busTypeVlnv?: VlnvDef;
  rawPortMaps?: RawPortMap[];
  ports?: BusPort[];
  [k: string]: unknown;
}
export interface ConduitPort {
  name?: string;
  width?: number | string;
  direction?: string;
  presence?: string;
  [k: string]: unknown;
}
export interface VlnvDef {
  vendor?: string;
  library?: string;
  name?: string;
  version?: string;
}
export interface RawPortMap {
  logical: string;
  physical: string;
  direction: 'in' | 'out';
  width: number;
}
export interface ElaboratePortWidth {
  iface_name: string;
  port_name: string;
  logical_name: string;
  direction: string;
  tcl_width: string;
}
export interface MemoryMap {
  name?: string;
  description?: string;
  address_blocks?: MemoryMapAddressBlock[];
  [k: string]: unknown;
}
export interface MemoryMapAddressBlock {
  name?: string;
  base_address?: number;
  baseAddress?: number;
  range?: number | number | string | null;
  usage?: string;
  registers?: MemoryMapRegister[];
  [k: string]: unknown;
}
export interface MemoryMapRegister {
  name?: string;
  offset?: number;
  address_offset?: number;
  addressOffset?: number;
  size?: number;
  access?: string;
  resetValue?: number;
  reset_value?: number;
  description?: string;
  fields?: MemoryMapField[];
  count?: number;
  stride?: number;
  registers?: MemoryMapRegister[];
  [k: string]: unknown;
}
export interface MemoryMapField {
  name?: string;
  bits?: string;
  offset?: number;
  bit_offset?: number;
  bitOffset?: number;
  width?: number;
  bit_width?: number;
  bitWidth?: number;
  access?: string;
  resetValue?: number;
  reset_value?: number;
  description?: string;
  monitorChangeOf?: string | null;
  [k: string]: unknown;
}
export interface ClockWithPeriod {
  name: string;
  frequency: string | null;
  period_ns: string | null;
}
