const fs = require('fs');
const path = require('path');
const { compile } = require('json-schema-to-typescript');

const REPO_ROOT = path.resolve(__dirname, '..');
const MEMORY_MAP_SCHEMA_PATH = path.join(
  REPO_ROOT,
  'node_modules',
  'ipcraft-spec',
  'schemas',
  'memory_map.schema.json'
);
const IP_CORE_SCHEMA_PATH = path.join(
  REPO_ROOT,
  'node_modules',
  'ipcraft-spec',
  'schemas',
  'ip_core.schema.json'
);
const TEMPLATE_CONTEXT_SCHEMA_PATH = path.join(
  REPO_ROOT,
  'src',
  'generator',
  'contract',
  'template_context.schema.json'
);

const MEMORY_MAP_OUTPUT_PATH = path.join(REPO_ROOT, 'src', 'domain', 'memorymap.types.ts');
const IP_CORE_OUTPUT_PATH = path.join(REPO_ROOT, 'src', 'domain', 'ipcore.types.ts');
const TEMPLATE_CONTEXT_OUTPUT_PATH = path.join(
  REPO_ROOT,
  'src',
  'generator',
  'contract',
  'templateContext.types.ts'
);

async function generate() {
  console.log('Generating domain types...');

  // 1. Generate memory map types
  if (!fs.existsSync(MEMORY_MAP_SCHEMA_PATH)) {
    throw new Error(`Memory Map schema not found at ${MEMORY_MAP_SCHEMA_PATH}`);
  }
  const rawMemoryMap = JSON.parse(fs.readFileSync(MEMORY_MAP_SCHEMA_PATH, 'utf8'));
  // Hoist $defs to root so that json-schema-to-typescript can resolve "#/$defs/..." pointers correctly
  const hoistedMemoryMap = {
    ...rawMemoryMap,
    $defs: rawMemoryMap.$defs || rawMemoryMap.items?.$defs,
  };

  const memoryMapTs = await compile(hoistedMemoryMap, 'MemoryMap', {
    bannerComment: `/**\n * This file was automatically generated by scripts/generate-types.js.\n * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n * and run npm run generate-types to regenerate this file.\n */`,
  });
  fs.writeFileSync(MEMORY_MAP_OUTPUT_PATH, memoryMapTs, 'utf8');
  console.log(`Generated ${MEMORY_MAP_OUTPUT_PATH}`);

  // 2. Generate IP core types
  if (!fs.existsSync(IP_CORE_SCHEMA_PATH)) {
    throw new Error(`IP Core schema not found at ${IP_CORE_SCHEMA_PATH}`);
  }
  const rawIpCore = JSON.parse(fs.readFileSync(IP_CORE_SCHEMA_PATH, 'utf8'));
  const ipCoreTs = await compile(rawIpCore, 'IpCore', {
    bannerComment: `/**\n * This file was automatically generated by scripts/generate-types.js.\n * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n * and run npm run generate-types to regenerate this file.\n */`,
  });
  fs.writeFileSync(IP_CORE_OUTPUT_PATH, ipCoreTs, 'utf8');
  console.log(`Generated ${IP_CORE_OUTPUT_PATH}`);

  // 3. Generate template context types
  if (!fs.existsSync(TEMPLATE_CONTEXT_SCHEMA_PATH)) {
    throw new Error(`Template context schema not found at ${TEMPLATE_CONTEXT_SCHEMA_PATH}`);
  }
  const rawTemplateContext = JSON.parse(fs.readFileSync(TEMPLATE_CONTEXT_SCHEMA_PATH, 'utf8'));
  const templateContextTs = await compile(rawTemplateContext, 'TemplateContext', {
    bannerComment: `/**\n * This file was automatically generated by scripts/generate-types.js.\n * DO NOT MODIFY IT BY HAND. Instead, modify template_context.schema.json,\n * and run npm run generate-types to regenerate this file.\n */`,
    additionalProperties: false,
  });
  fs.writeFileSync(TEMPLATE_CONTEXT_OUTPUT_PATH, templateContextTs, 'utf8');
  console.log(`Generated ${TEMPLATE_CONTEXT_OUTPUT_PATH}`);

  console.log('Domain types generation complete.');
}

generate().catch((err) => {
  console.error('Error generating types:', err);
  process.exit(1);
});
