# Quartus synthesis project for led_controller_avmm
# Generated by IPCraft
#
# Target device : 5CSEBA6U23I7 (Cyclone V)
#
# Usage (batch — run from the altera/ directory):
#   quartus_sh --flow compile led_controller_avmm
#
# All I/O ports are marked as virtual pins so timing analysis runs without
# board pin assignments, which is sufficient for IP-core timing verification.

package require ::quartus::project

set script_dir   [file normalize [file dirname [info script]]]
set project_name led_controller_avmm

# Gracefully handle already open projects in active session to prevent locking/corruption
if {[is_project_open]} {
    puts "Closing currently open project: [get_current_project]"
    project_close
}

# Remove any existing project files to allow a clean re-run
foreach f [glob -nocomplain $project_name.qpf $project_name.qsf] {
    file delete -force $f
}
foreach d [list db incremental_db] {
    if {[file isdirectory $d]} { file delete -force $d }
}

puts "=== Creating Quartus project ==="
puts "Project : $project_name"
puts "Device  : 5CSEBA6U23I7"
puts "Dir     : $script_dir"

project_new $project_name -revision $project_name -overwrite

# ---- Device settings --------------------------------------------------------
set_global_assignment -name FAMILY "Cyclone V"
set_global_assignment -name DEVICE 5CSEBA6U23I7
set_global_assignment -name VHDL_INPUT_VERSION VHDL_2008
set_global_assignment -name TOP_LEVEL_ENTITY led_controller_avmm

# ---- RTL source files -------------------------------------------------------
# Paths are relative to this QSF (in build/) so the project is portable across
# host and Docker environments — no absolute paths are stored.
set_global_assignment -name VHDL_FILE [file join .. ../rtl/led_controller_avmm_pkg.vhd]
set_global_assignment -name VHDL_FILE [file join .. ../rtl/led_controller_avmm_regs.vhd]
set_global_assignment -name VHDL_FILE [file join .. ../rtl/led_controller_avmm_core.vhd]
set_global_assignment -name VHDL_FILE [file join .. ../rtl/led_controller_avmm_avmm.vhd]
set_global_assignment -name VHDL_FILE [file join .. ../rtl/led_controller_avmm.vhd]

# ---- Timing constraints -----------------------------------------------------
# sdc_file is a bare filename (the .sdc is written as a sibling of this
# project.tcl in altera/, unlike rtl_files which live one level up in
# ../rtl/) -- no [file join ..] wrapper needed. Confirmed on a real Quartus
# run: wrapping it the same way as rtl_files produced
# "Synopsys Design Constraints File file not found" and unconstrained
# (negative-slack) timing analysis.
set_global_assignment -name SDC_FILE led_controller_avmm.sdc

# ---- Virtual pins -----------------------------------------------------------
# Marks every top-level I/O as a virtual (unconstrained) pin so that Quartus
# runs synthesis and timing analysis without requiring board pin assignments.
set_instance_assignment -name VIRTUAL_PIN ON -to *

project_close

puts ""
puts "Project ready.  Run full compilation with:"
puts "  quartus_sh --flow compile $project_name"
puts "Timing report will be written to output_files/${project_name}.sta.summary"
