# led_controller_avmm_hw.tcl - Altera Platform Designer Component Definition
# Generated by ipcraft VHDL Generator
#
# Provides component integration for Altera Quartus Platform Designer (Qsys)
# with Avalon-MM slave interface for register access.
#
# Usage: Place this file in the same directory as your RTL files and
# add the directory to Platform Designer's IP search path.

# -----------------------------------------------------------------------------
# Package Definition
# -----------------------------------------------------------------------------
package require qsys

# -----------------------------------------------------------------------------
# Module Properties
# -----------------------------------------------------------------------------
set_module_property DESCRIPTION "Avalon-MM peripheral for the DE10-Nano LED demo. Drives 8 board LEDs from a software-writable pattern register and exposes a free-running heartbeat status bit with a sticky change-of-state event.
"
set_module_property NAME led_controller_avmm
set_module_property VERSION 1.0.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "ipcraft-examples"
set_module_property DISPLAY_NAME "Led Controller Avmm"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false

# -----------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Clock Interface
# -----------------------------------------------------------------------------
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1

# -----------------------------------------------------------------------------
# Reset Interface
# -----------------------------------------------------------------------------
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1

# -----------------------------------------------------------------------------
# Bus Interfaces (Generic)
# -----------------------------------------------------------------------------

# Interface: S_AVMM (ipcraft:busif:avalon_mm:1.0)
add_interface S_AVMM avalon end
set_interface_property S_AVMM associatedClock clk
set_interface_property S_AVMM associatedReset reset
set_interface_property S_AVMM ENABLED true
set_interface_property S_AVMM EXPORT_OF ""
set_interface_property S_AVMM PORT_NAME_MAP ""
set_interface_property S_AVMM CMSIS_SVD_VARIABLES ""
set_interface_property S_AVMM SVD_ADDRESS_GROUP ""

# Type-specific properties
set_interface_property S_AVMM addressUnits WORDS
set_interface_property S_AVMM maximumPendingReadTransactions 0
# Ports
add_interface_port S_AVMM avs_address address Input 2
add_interface_port S_AVMM avs_read read Input 1
add_interface_port S_AVMM avs_write write Input 1
add_interface_port S_AVMM avs_byteenable byteenable Input 4
add_interface_port S_AVMM avs_writedata writedata Input 32
add_interface_port S_AVMM avs_readdata readdata Output 32


# Conduit interface for user port: led
add_interface led conduit end
set_interface_property led associatedClock clk
set_interface_property led associatedReset reset
set_interface_property led ENABLED true
set_interface_property led EXPORT_OF ""
set_interface_property led PORT_NAME_MAP ""
set_interface_property led CMSIS_SVD_VARIABLES ""
set_interface_property led SVD_ADDRESS_GROUP ""

add_interface_port led led led Output 8


# -----------------------------------------------------------------------------
# Interrupt Interface(s)
# -----------------------------------------------------------------------------


# -----------------------------------------------------------------------------
# File Sets
# -----------------------------------------------------------------------------
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL led_controller_avmm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file led_controller_avmm_pkg.vhd VHDL PATH ../../rtl/led_controller_avmm_pkg.vhd
add_fileset_file led_controller_avmm_regs.vhd VHDL PATH ../../rtl/led_controller_avmm_regs.vhd
add_fileset_file led_controller_avmm_core.vhd VHDL PATH ../../rtl/led_controller_avmm_core.vhd
add_fileset_file led_controller_avmm_avmm.vhd VHDL PATH ../../rtl/led_controller_avmm_avmm.vhd
add_fileset_file led_controller_avmm.vhd VHDL PATH ../../rtl/led_controller_avmm.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL led_controller_avmm
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file led_controller_avmm_pkg.vhd VHDL PATH ../../rtl/led_controller_avmm_pkg.vhd
add_fileset_file led_controller_avmm_regs.vhd VHDL PATH ../../rtl/led_controller_avmm_regs.vhd
add_fileset_file led_controller_avmm_core.vhd VHDL PATH ../../rtl/led_controller_avmm_core.vhd
add_fileset_file led_controller_avmm_avmm.vhd VHDL PATH ../../rtl/led_controller_avmm_avmm.vhd
add_fileset_file led_controller_avmm.vhd VHDL PATH ../../rtl/led_controller_avmm.vhd TOP_LEVEL_FILE
