#!/usr/bin/env bash
#
# validate_pd.sh
#
# Validates generated _hw.tcl files using Platform Designer's BFM testbench
# generation (qsys-generate --testbench=STANDARD).
#
# For each hw.tcl: locates the companion test.qsys (generated by IPCraft in the
# same altera/ directory) which instantiates the component with all interfaces
# exported to the system boundary.  Runs qsys-generate --testbench=STANDARD on
# that file.  With all interfaces exported, Platform Designer's system validation
# passes and the BFM testbench generator can auto-connect clock/reset/Avalon/AXI/
# conduit BFMs to each exported interface.
#
# This catches real interface errors such as AXI-stream port role mismatches
# without the false positives from a bare unconnected system.
#
# Each unique IP name is validated only once — VHDL and SV fixture variants
# produce the same Platform Designer component structure, so duplicates are skipped.
#
# Usage:
#   validate_pd.sh <hw_tcl_path> [<hw_tcl_path> ...]
#
# Exit codes:
#   0  — all components PASS
#   1  — one or more components FAIL
#   2  — qsys-generate not found (caller may treat as skip)

# ── Locate qsys-generate ────────────────────────────────────────────────────
if command -v qsys-generate > /dev/null 2>&1; then
    QSYS_GENERATE="qsys-generate"
elif [ -x "/opt/intelFPGA/quartus/sopc_builder/bin/qsys-generate" ]; then
    QSYS_GENERATE="/opt/intelFPGA/quartus/sopc_builder/bin/qsys-generate"
elif [ -x "/opt/intelFPGA/quartus/bin/qsys-generate" ]; then
    QSYS_GENERATE="/opt/intelFPGA/quartus/bin/qsys-generate"
else
    echo "ERROR: qsys-generate not found in PATH or standard Quartus locations" >&2
    exit 2
fi

total_errors=0
# Track validated IP names to skip duplicate VHDL/SV fixture pairs.
declare -A seen_ips

for hw_tcl in "$@"; do
    if [ ! -f "$hw_tcl" ]; then
        echo ""
        echo "FAIL: file not found: $hw_tcl"
        total_errors=$((total_errors + 1))
        continue
    fi

    ip_dir=$(dirname "$hw_tcl")

    # Extract the component NAME from the hw.tcl
    ip_name=$(grep 'set_module_property[[:space:]]*NAME[[:space:]]' "$hw_tcl" \
        | sed 's/.*NAME[[:space:]]*//' \
        | sed 's/[[:space:]].*//' \
        | tr -d '"{}' \
        | head -1)

    if [ -z "$ip_name" ]; then
        echo ""
        echo "FAIL: could not find set_module_property NAME in $hw_tcl"
        total_errors=$((total_errors + 1))
        continue
    fi

    # Skip if this IP name was already validated (VHDL/SV duplicates).
    if [ "${seen_ips[$ip_name]+_}" ]; then
        echo "Skipping $ip_name (already validated)"
        continue
    fi
    seen_ips[$ip_name]=1

    # Locate the companion test.qsys generated by IPCraft alongside the hw.tcl.
    # This file instantiates the component with all interfaces exported to the
    # system boundary, which is required for --testbench=STANDARD to work.
    test_qsys="${ip_dir}/test.qsys"
    if [ ! -f "$test_qsys" ]; then
        echo ""
        echo "FAIL: test.qsys not found at $test_qsys"
        echo "  Regenerate the fixture so IPCraft produces test.qsys alongside the hw.tcl."
        total_errors=$((total_errors + 1))
        continue
    fi

    echo ""
    echo "======================================================"
    echo "=== Validating via Platform Designer BFM testbench: $(basename "$hw_tcl")"
    echo "======================================================"
    echo "Found IP component name: $ip_name"

    tmp_dir=$(mktemp -d)

    pd_output=$("$QSYS_GENERATE" \
        --search-path="${ip_dir},$" \
        --testbench=STANDARD \
        --output-directory="$tmp_dir" \
        "$test_qsys" 2>&1)
    pd_exit=$?

    echo "$pd_output"

    if [ $pd_exit -eq 0 ]; then
        echo "PASS: $ip_name passed Platform Designer BFM testbench validation"
    else
        # qsys-generate prefixes every message with a timestamp, e.g.:
        #   "2026.06.28.23:29:05 Error: Master ... port role mismatch: tstrb"
        # Match "Error:" with an optional leading timestamp (space before Error).
        # Filter the generic summary line — the specific errors above it are
        # already displayed and counted.
        component_errors=$(echo "$pd_output" | grep -E '(^| )Error:' \
            | grep -v 'There were errors creating the testbench system')

        if [ -z "$component_errors" ]; then
            echo "PASS: $ip_name (warnings only, testbench generation succeeded structurally)"
        else
            echo "FAIL: $ip_name has component-level errors:"
            echo "$component_errors"
            total_errors=$((total_errors + 1))
        fi
    fi

    rm -rf "$tmp_dir"
done

echo ""
echo "======================================================"
if [ "$total_errors" -eq 0 ]; then
    echo "OVERALL PASS: all hw.tcl files validated successfully"
else
    echo "OVERALL FAIL: $total_errors error(s) across all files"
fi
echo "======================================================"

exit $((total_errors > 0 ? 1 : 0))
