

--------------------------------------------------------------------------------
-- Entity: regmap_conformance
-- Description: Hardware register-conformance test IP (cvsoc roadmap, ipcraft-vscode docs/hardware-conformance-test-plan.md). Exercises all seven IPCraft field access types plus change-of-state, register arrays, byte strobes, mixed registers, and enumerated/non-zero-reset fields, self-checked via a software-writable STIMULUS loopback register.

-- Generated by ipcraft VHDL Generator
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.regmap_conformance_pkg.all;

entity regmap_conformance is
  port (
    -- Clock and reset
    clk : in std_logic;
    reset : in std_logic;


    -- S_AVMM (SLAVE)
    avs_address    : in  std_logic_vector(4 downto 0);
    avs_read       : in  std_logic;
    avs_write      : in  std_logic;
    avs_byteenable : in  std_logic_vector(3 downto 0);
    avs_writedata  : in  std_logic_vector(31 downto 0);
    avs_readdata   : out std_logic_vector(31 downto 0)
    );
end entity regmap_conformance;

architecture rtl of regmap_conformance is

    -- Internal register signals
  signal regs_sw2hw : t_regs_sw2hw;
  signal regs_hw2sw : t_regs_hw2sw;

begin


    ----------------------------------------------------------------------------
    -- Bus Wrapper Instance
    ----------------------------------------------------------------------------
    u_avmm : entity work.regmap_conformance_avmm
    port map (
      clk => clk,
      rst => reset,

      avs_address    => avs_address,
      avs_read       => avs_read,
      avs_write      => avs_write,
      avs_byteenable => avs_byteenable,
      avs_writedata  => avs_writedata,
      avs_readdata   => avs_readdata,
      regs_out => regs_sw2hw,
      regs_in  => regs_hw2sw
    );

    ----------------------------------------------------------------------------
    -- Core Logic Instance
    ----------------------------------------------------------------------------
    u_core : entity work.regmap_conformance_core
    port map (
      clk => clk,
      rst => reset,
      regs_in  => regs_sw2hw,
      regs_out => regs_hw2sw
    );

end architecture rtl;
