


--------------------------------------------------------------------------------
-- Entity: regmap_conformance_regs
-- Description: Register bank with software/hardware access interface
-- Generated by ipcraft VHDL Generator
--
-- This is a bus-agnostic register bank that provides:
-- - Register storage for SW-writable registers
-- - Pulse generation for write-1-to-clear fields
-- - Clean interface for hardware logic access
--
-- Connect to a bus wrapper (AXI-Lite, Avalon-MM, etc.) for host access.
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.regmap_conformance_pkg.all;

entity regmap_conformance_regs is
  port (
    -- Clock and reset
    clk : in std_logic;
    rst : in std_logic;

    -- Write interface (from bus wrapper)
    wr_en   : in  std_logic;
    wr_addr : in  std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    wr_data : in  std_logic_vector(C_DATA_WIDTH-1 downto 0);
    wr_strb : in  std_logic_vector((C_DATA_WIDTH/8)-1 downto 0);

    -- Read interface (from bus wrapper)
    rd_en   : in  std_logic;
    rd_addr : in  std_logic_vector(C_ADDR_WIDTH-1 downto 0);
    rd_data : out std_logic_vector(C_DATA_WIDTH-1 downto 0);
    rd_valid: out std_logic;

    -- Register interface to core logic
    regs_out : out t_regs_sw2hw;  -- SW-writable registers (to core)
    regs_in  : in  t_regs_hw2sw   -- HW status registers + W1C event pulses + CoS values (from core)
  );
end entity regmap_conformance_regs;

architecture rtl of regmap_conformance_regs is

  -- Internal register storage
  signal regs : t_regs_sw2hw := C_REGS_SW2HW_RESET;

  -- Read data pipeline
  signal rd_data_int  : std_logic_vector(C_DATA_WIDTH-1 downto 0);
  signal rd_valid_int : std_logic;

  -- Shadow registers and CoS pulse signals for change-of-state detection
  signal link_speed_shadow : std_logic_vector(3 downto 0) := (others => '0');
  signal link_speed_changed_cos : std_logic;

  -- Apply write strobe to data
  function apply_wstrb(
    old_data : std_logic_vector(C_DATA_WIDTH-1 downto 0);
    new_data : std_logic_vector(C_DATA_WIDTH-1 downto 0);
    wstrb    : std_logic_vector((C_DATA_WIDTH/8)-1 downto 0)
  ) return std_logic_vector is
    variable result : std_logic_vector(C_DATA_WIDTH-1 downto 0);
  begin
    for i in 0 to (C_DATA_WIDTH/8)-1 loop
      if wstrb(i) = '1' then
        result(i*8+7 downto i*8) := new_data(i*8+7 downto i*8);
      else
        result(i*8+7 downto i*8) := old_data(i*8+7 downto i*8);
      end if;
    end loop;
    return result;
  end function;

begin

  -- Output register values to core
  regs_out <= regs;
  rd_data  <= rd_data_int;
  rd_valid <= rd_valid_int;

  -- Combinatorial CoS pulse detection (current value vs shadow)
  link_speed_changed_cos <= '1' when regs_in.link_val.speed /= link_speed_shadow else '0';

  ----------------------------------------------------------------------------
  -- Write Process
  ----------------------------------------------------------------------------
  p_write : process(clk)
    variable v_addr_index : natural;
    variable v_wdata      : std_logic_vector(C_DATA_WIDTH-1 downto 0);
  begin
    if rising_edge(clk) then
      if rst = '1' then
        regs <= C_REGS_SW2HW_RESET;
        -- Shadow registers reset to the monitored field's own reset value, so
        -- the first post-reset comparison is always a match (no spurious
        -- change-of-state event; also removes the undefined-power-up-state
        -- risk on real hardware, since this is now an explicit sync reset).
        link_speed_shadow <= (others => '0');
      else
        v_addr_index := to_integer(unsigned(wr_addr(C_ADDR_WIDTH-1 downto 0)));

        -- Shadow register updates (capture monitored field values every clock)
        link_speed_shadow <= regs_in.link_val.speed;

        -- W1C arbitration: hardware event-set has priority over CPU Write-1-to-Clear.
        -- Runs every clock cycle so no pulse is missed even when the CPU is not writing.
        if regs_in.int_status_pulse.sample_evt_pulse = '1' then
          regs.int_status.sample_evt <= '1';
        elsif wr_en = '1' and v_addr_index = C_REG_INT_STATUS_ADDR
              and wr_strb(0) = '1' and wr_data(0) = '1' then
          regs.int_status.sample_evt <= '0';
        end if;
        if regs_in.int_status_pulse.error_evt_pulse = '1' then
          regs.int_status.error_evt <= '1';
        elsif wr_en = '1' and v_addr_index = C_REG_INT_STATUS_ADDR
              and wr_strb(0) = '1' and wr_data(1) = '1' then
          regs.int_status.error_evt <= '0';
        end if;
        if regs_in.irq_legacy_pulse.flag_pulse = '1' then
          regs.irq_legacy.flag <= '1';
        elsif wr_en = '1' and v_addr_index = C_REG_IRQ_LEGACY_ADDR
              and wr_strb(0) = '1' and wr_data(0) = '1' then
          regs.irq_legacy.flag <= '0';
        end if;

        -- SC arbitration: hardware event-clear has priority over CPU set.
        -- Runs every clock cycle so no pulse is missed even when the CPU is not writing.
        if regs_in.command_clear.start_clear = '1' then
          regs.command.start <= '0';
        elsif wr_en = '1' and v_addr_index = C_REG_COMMAND_ADDR
              and wr_strb(0) = '1' and wr_data(0) = '1' then
          regs.command.start <= '1';
        end if;
        if regs_in.busy_clear.active_clear = '1' then
          regs.busy.active <= '0';
        elsif wr_en = '1' and v_addr_index = C_REG_BUSY_ADDR
              and wr_strb(0) = '1' and wr_data(0) = '1' then
          regs.busy.active <= '1';
        end if;

        -- CoS W1C arbitration (internally generated change-of-state pulse)
        if link_speed_changed_cos = '1' then
          regs.link.speed_changed <= '1';
        elsif wr_en = '1' and v_addr_index = C_REG_LINK_ADDR
              and wr_strb(1) = '1' and wr_data(8) = '1' then
          regs.link.speed_changed <= '0';
        end if;

        if wr_en = '1' then
          case v_addr_index is
          when C_REG_SCRATCH_ADDR =>
            v_wdata := apply_wstrb(to_slv(regs.scratch), wr_data, wr_strb);
            regs.scratch <= to_scratch(v_wdata);
          when C_REG_STIMULUS_ADDR =>
            v_wdata := apply_wstrb(to_slv(regs.stimulus), wr_data, wr_strb);
            regs.stimulus <= to_stimulus(v_wdata);
          when C_REG_INT_STATUS_ADDR =>
            v_wdata := apply_wstrb(to_slv(regs.int_status), wr_data, wr_strb);
          when C_REG_IRQ_LEGACY_ADDR =>
            v_wdata := apply_wstrb(to_slv(regs.irq_legacy), wr_data, wr_strb);
          when C_REG_DIAG_ADDR =>
            v_wdata := apply_wstrb(to_slv(regs.diag), wr_data, wr_strb);
            regs.diag <= to_diag(v_wdata);
          when C_REG_LINK_ADDR =>
            v_wdata := apply_wstrb(to_slv(regs.link), wr_data, wr_strb);
          when C_REG_CONTROL_ADDR =>
            v_wdata := apply_wstrb(to_slv(regs.control), wr_data, wr_strb);
            regs.control <= to_control(v_wdata);
          when C_REG_CHANNEL_0_CONFIG_ADDR =>
            v_wdata := apply_wstrb(to_slv(regs.channel_0_config), wr_data, wr_strb);
            regs.channel_0_config <= to_channel_0_config(v_wdata);
          when C_REG_CHANNEL_1_CONFIG_ADDR =>
            v_wdata := apply_wstrb(to_slv(regs.channel_1_config), wr_data, wr_strb);
            regs.channel_1_config <= to_channel_1_config(v_wdata);
          when others =>
            null;
          end case;
        end if;
      end if;
    end if;
  end process;

  ----------------------------------------------------------------------------
  -- Read Process
  ----------------------------------------------------------------------------
  p_read : process(clk)
    variable v_addr_index : natural;
    variable v_rd_data    : std_logic_vector(C_DATA_WIDTH-1 downto 0);
  begin
    if rising_edge(clk) then
      rd_valid_int <= '0';

      if rst = '1' then
        rd_data_int  <= (others => '0');
        rd_valid_int <= '0';
      elsif rd_en = '1' then
        v_addr_index := to_integer(unsigned(rd_addr(C_ADDR_WIDTH-1 downto 0)));

        case v_addr_index is
          when C_REG_ID_ADDR =>
            rd_data_int <= to_slv(regs_in.id);
          when C_REG_SCRATCH_ADDR =>
            rd_data_int <= to_slv(regs.scratch);
          when C_REG_STIMULUS_ADDR =>
            rd_data_int <= to_slv(regs.stimulus);
          when C_REG_STATUS_ADDR =>
            rd_data_int <= to_slv(regs_in.status);
          when C_REG_INT_STATUS_ADDR =>
            rd_data_int <= to_slv(regs.int_status);
          when C_REG_BUSY_ADDR =>
            rd_data_int <= to_slv(regs.busy);
          when C_REG_WO_MIRROR_ADDR =>
            rd_data_int <= to_slv(regs_in.wo_mirror);
          when C_REG_CONTROL_ADDR =>
            rd_data_int <= to_slv(regs.control);
          when C_REG_CHANNEL_0_CONFIG_ADDR =>
            rd_data_int <= to_slv(regs.channel_0_config);
          when C_REG_CHANNEL_0_COUNT_ADDR =>
            rd_data_int <= to_slv(regs_in.channel_0_count);
          when C_REG_CHANNEL_1_CONFIG_ADDR =>
            rd_data_int <= to_slv(regs.channel_1_config);
          when C_REG_CHANNEL_1_COUNT_ADDR =>
            rd_data_int <= to_slv(regs_in.channel_1_count);
          when C_REG_LINK_ADDR =>
            v_rd_data := (others => '0');
            v_rd_data(3 downto 0) := regs_in.link_val.speed;
            v_rd_data(8) := regs.link.speed_changed;
            rd_data_int <= v_rd_data;
          when others =>
            rd_data_int <= (others => '0');
        end case;

        rd_valid_int <= '1';
      end if;
    end if;
  end process;

end architecture rtl;
