

--------------------------------------------------------------------------------
-- Package: led_controller_avmm_pkg
-- Generated by ipcraft VHDL Generator
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package led_controller_avmm_pkg is

  ----------------------------------------------------------------------------
  -- Constants
  ----------------------------------------------------------------------------
  constant C_DATA_WIDTH : natural := 32;
  constant C_ADDR_WIDTH : natural := 4;
  constant C_REG_WIDTH  : natural := 4;  -- Bytes per register

  ----------------------------------------------------------------------------
  -- Register Address Map (byte offset, matches the resolved memory map and
  -- the generated component.xml -- never derived from declaration order)
  ----------------------------------------------------------------------------
  constant C_REG_VERSION_ADDR : natural := 0;  -- addr 00
  constant C_REG_LED_PATTERN_ADDR : natural := 4;  -- addr 04
  constant C_REG_EVENTS_ADDR : natural := 8;  -- addr 08

  ----------------------------------------------------------------------------
  -- Register Record Types
  ----------------------------------------------------------------------------

  -- VERSION register fields
  type t_reg_version is record
    minor : std_logic_vector(7 downto 0);  -- bits 7:0
    major : std_logic_vector(7 downto 0);  -- bits 15:8
  end record;

  constant C_REG_VERSION_RESET : t_reg_version := (
    minor => (others => '0'),
    major => "00000001"
  );

  function to_slv(reg : t_reg_version) return std_logic_vector;
  function to_version(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_version;

  -- LED_PATTERN register fields
  type t_reg_led_pattern is record
    pattern : std_logic_vector(7 downto 0);  -- bits 7:0
  end record;

  constant C_REG_LED_PATTERN_RESET : t_reg_led_pattern := (
    pattern => (others => '0')
  );

  function to_slv(reg : t_reg_led_pattern) return std_logic_vector;
  function to_led_pattern(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_led_pattern;

  -- EVENTS register fields
  type t_reg_events is record
    heartbeat_active : std_logic;  -- bit 0
    heartbeat_toggled : std_logic;  -- bit 1
  end record;

  constant C_REG_EVENTS_RESET : t_reg_events := (
    heartbeat_active => '0',
    heartbeat_toggled => '0'
  );

  function to_slv(reg : t_reg_events) return std_logic_vector;
  function to_events(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_events;

  -- W1C event-pulse record types (hardware drives a 1-cycle strobe to set a sticky bit)

  -- Hardware-driven value-port record types: live values for read-only fields
  -- mixed into an otherwise SW-writable register (includes CoS-monitored
  -- fields, which are always mixed by construction).

  type t_reg_events_val is record
    heartbeat_active : std_logic;  -- hardware-driven, read-only in EVENTS
  end record;

  constant C_REG_EVENTS_VAL_RESET : t_reg_events_val := (
    heartbeat_active => '0'
  );

  ----------------------------------------------------------------------------
  -- Aggregate Register Records (for clean port interface)
  ----------------------------------------------------------------------------

  -- SW -> HW: Registers written by software, read by hardware
  type t_regs_sw2hw is record
    led_pattern : t_reg_led_pattern;
    events : t_reg_events;
  end record;

  constant C_REGS_SW2HW_RESET : t_regs_sw2hw := (
    led_pattern => C_REG_LED_PATTERN_RESET,
    events => C_REG_EVENTS_RESET
  );

  -- HW -> SW: Status registers (RO) + W1C/SC event pulses + hardware-driven value ports
  type t_regs_hw2sw is record
    version : t_reg_version;
    events_val : t_reg_events_val;  -- hardware-driven values for EVENTS
  end record;

  constant C_REGS_HW2SW_RESET : t_regs_hw2sw := (
    version => C_REG_VERSION_RESET,
    events_val => C_REG_EVENTS_VAL_RESET
  );

end package led_controller_avmm_pkg;


package body led_controller_avmm_pkg is

  ----------------------------------------------------------------------------
  -- Conversion Functions
  ----------------------------------------------------------------------------

  -- VERSION conversions
  function to_slv(reg : t_reg_version) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(7 downto 0) := reg.minor;
    slv(15 downto 8) := reg.major;
    return slv;
  end function;

  function to_version(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_version is
    variable reg : t_reg_version;
  begin
    reg.minor := slv(7 downto 0);
    reg.major := slv(15 downto 8);
    return reg;
  end function;

  -- LED_PATTERN conversions
  function to_slv(reg : t_reg_led_pattern) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(7 downto 0) := reg.pattern;
    return slv;
  end function;

  function to_led_pattern(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_led_pattern is
    variable reg : t_reg_led_pattern;
  begin
    reg.pattern := slv(7 downto 0);
    return reg;
  end function;

  -- EVENTS conversions
  function to_slv(reg : t_reg_events) return std_logic_vector is
    variable slv : std_logic_vector(C_DATA_WIDTH-1 downto 0) := (others => '0');
  begin
    slv(0) := reg.heartbeat_active;
    slv(1) := reg.heartbeat_toggled;
    return slv;
  end function;

  function to_events(slv : std_logic_vector(C_DATA_WIDTH-1 downto 0)) return t_reg_events is
    variable reg : t_reg_events;
  begin
    reg.heartbeat_active := slv(0);
    reg.heartbeat_toggled := slv(1);
    return reg;
  end function;

end package body led_controller_avmm_pkg;
