

--------------------------------------------------------------------------------
-- Entity: led_controller_avmm
-- Description: Avalon-MM peripheral for the DE10-Nano LED demo. Drives 8 board LEDs from a software-writable pattern register and exposes a free-running heartbeat status bit with a sticky change-of-state event.

-- Generated by ipcraft VHDL Generator
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.led_controller_avmm_pkg.all;

entity led_controller_avmm is
  port (
    -- Clock and reset
    clk : in std_logic;
    reset : in std_logic;


    -- S_AVMM (SLAVE)
    avs_address    : in  std_logic_vector(1 downto 0);
    avs_read       : in  std_logic;
    avs_write      : in  std_logic;
    avs_byteenable : in  std_logic_vector(3 downto 0);
    avs_writedata  : in  std_logic_vector(31 downto 0);
    avs_readdata   : out std_logic_vector(31 downto 0);

    -- User ports
    led : out std_logic_vector(7 downto 0)
    );
end entity led_controller_avmm;

architecture rtl of led_controller_avmm is

    -- Internal register signals
  signal regs_sw2hw : t_regs_sw2hw;
  signal regs_hw2sw : t_regs_hw2sw;

begin


    ----------------------------------------------------------------------------
    -- Bus Wrapper Instance
    ----------------------------------------------------------------------------
    u_avmm : entity work.led_controller_avmm_avmm
    port map (
      clk => clk,
      rst => reset,

      avs_address    => avs_address,
      avs_read       => avs_read,
      avs_write      => avs_write,
      avs_byteenable => avs_byteenable,
      avs_writedata  => avs_writedata,
      avs_readdata   => avs_readdata,
      regs_out => regs_sw2hw,
      regs_in  => regs_hw2sw
    );

    ----------------------------------------------------------------------------
    -- Core Logic Instance
    ----------------------------------------------------------------------------
    u_core : entity work.led_controller_avmm_core
    port map (
      clk => clk,
      rst => reset,
      regs_in  => regs_sw2hw,
      regs_out => regs_hw2sw,
      led => led
    );

end architecture rtl;
