

--------------------------------------------------------------------------------
-- Entity: led_controller_avmm_core
-- Description: Core logic module (bus-agnostic)
-- Generated by ipcraft VHDL Generator
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.led_controller_avmm_pkg.all;

entity led_controller_avmm_core is
  port (
    -- Clock and reset
    clk : in std_logic;
    rst : in std_logic;

    -- Register interface (record-based)
    regs_in : in t_regs_sw2hw; -- SW-writable registers (from bus wrapper)
    regs_out : out t_regs_hw2sw; -- HW-status / W1C pulses / CoS values (to bus wrapper)

    -- User ports
    led : out std_logic_vector(7 downto 0)
    );
end entity led_controller_avmm_core;

architecture rtl of led_controller_avmm_core is

  ----------------------------------------------------------------------------
  -- Internal Signals
  ----------------------------------------------------------------------------
  -- Free-running divider driving the heartbeat: toggling the top bit of a
  -- 25-bit counter at 50 MHz gives a ~0.75 Hz square wave ("roughly once per
  -- second", per the .mm.yml description). The register file computes
  -- EVENTS.HEARTBEAT_TOGGLED from this level automatically (monitorChangeOf).
  constant C_HEARTBEAT_DIV_BITS : natural := 25;
  signal heartbeat_counter : unsigned(C_HEARTBEAT_DIV_BITS-1 downto 0) := (others => '0');

begin

  -- LED passthrough: software writes to LED_PATTERN drive the LEDs directly.
  led <= regs_in.led_pattern.pattern;

  ----------------------------------------------------------------------------
  -- Main Process
  ----------------------------------------------------------------------------
  p_main : process(clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        -- Reset logic
        regs_out <= C_REGS_HW2SW_RESET;
        heartbeat_counter <= (others => '0');
      else
        heartbeat_counter <= heartbeat_counter + 1;

        regs_out.version <= C_REG_VERSION_RESET;
        regs_out.events_val.heartbeat_active <= heartbeat_counter(heartbeat_counter'high);
      end if;
    end if;
  end process;

end architecture rtl;
