

--------------------------------------------------------------------------------
-- Entity: led_controller_avmm_avmm
-- Description: Avalon-MM slave interface for register access
-- Generated by ipcraft VHDL Generator
--
-- Register Map:
--   0000 : VERSION (read-only)
--   0004 : LED_PATTERN (read-write)
--   0008 : EVENTS (read-write)
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.led_controller_avmm_pkg.all;

entity led_controller_avmm_avmm is
  port (
    -- Clock and reset
    clk : in std_logic;
    rst : in std_logic;

    -- Avalon-MM Slave Interface
    avs_address      : in  std_logic_vector(1 downto 0);
    avs_read         : in  std_logic;
    avs_write        : in  std_logic;
    avs_byteenable   : in  std_logic_vector(3 downto 0);
    avs_writedata    : in  std_logic_vector(31 downto 0);
    avs_readdata     : out std_logic_vector(31 downto 0);

    -- Register interface
    regs_out : out t_regs_sw2hw;  -- To core (SW-writable)
    regs_in  : in  t_regs_hw2sw   -- From core (HW-writable / W1C pulses / CoS values)
  );
end entity led_controller_avmm_avmm;

architecture rtl of led_controller_avmm_avmm is

  -- Bus Internal Signals
  signal address       : std_logic_vector(C_ADDR_WIDTH-1 downto 0);
  signal read          : std_logic;
  signal write         : std_logic;
  signal writedata     : std_logic_vector(C_DATA_WIDTH-1 downto 0);
  signal byteenable    : std_logic_vector((C_DATA_WIDTH/8)-1 downto 0);
  signal readdata      : std_logic_vector(C_DATA_WIDTH-1 downto 0);
  signal readdatavalid : std_logic;
  signal waitrequest   : std_logic;

begin

  ----------------------------------------------------------------------------
  -- Bus Interface Connections
  ----------------------------------------------------------------------------
address   <= avs_address & "00";
  read      <= avs_read;
  write     <= avs_write;
  writedata <= avs_writedata;
  byteenable <= avs_byteenable;
  avs_readdata <= readdata;

  ----------------------------------------------------------------------------
  -- Bus Logic
  ----------------------------------------------------------------------------

  -- No wait states
  waitrequest <= '0';

  ----------------------------------------------------------------------------
  -- Register Bank Instantiation
  ----------------------------------------------------------------------------
  u_regs : entity work.led_controller_avmm_regs
    port map (
      clk      => clk,
      rst      => rst,
      wr_en    => write,
      wr_addr  => address,
      wr_data  => writedata,
      wr_strb  => byteenable,
      rd_en    => read,
      rd_addr  => address,
      rd_data  => readdata,
      rd_valid => readdatavalid,
      regs_out => regs_out,
      regs_in  => regs_in
    );

end architecture rtl;
