/**
 * Quartus integration tests.
 *
 * Two levels of hw.tcl validation.  Supports two execution modes:
 *
 *   docker  — run inside cvsoc/quartus:23.1 via Docker (original mode).
 *             Activated automatically when the Docker image is present.
 *
 *   native  — run using host-installed Quartus binaries.
 *             Activated when QUARTUS_TCLSH_BIN and QUARTUS_SH_BIN are set
 *             and Docker is not available.  Useful on machines that have
 *             Quartus installed locally but not Docker.
 *
 *   1. Stub validation (tier 1): tclsh validate.tcl — sources each _hw.tcl
 *      with Platform Designer API stubs, calls elaborate/validate callbacks,
 *      and checks structural correctness.  Fast (~ms per file).
 *
 *   2. BFM testbench validation (tier 1 on Docker, tier 2 on qsys-generate):
 *      validate_pd.sh — uses the companion test.qsys generated by IPCraft and
 *      runs qsys-generate --testbench=STANDARD.  In native mode this test is
 *      skipped (qsys-generate is only available in the full Platform Designer
 *      suite, not in the lite Quartus install).
 *      Set REQUIRE_QSYS_GENERATE=1 to fail instead of skip.
 *
 * The tests self-skip when neither Docker nor native Quartus binaries are
 * available.  Set SKIP_DOCKER=1 to explicitly skip even when Docker is present
 * (native mode is then used if QUARTUS_TCLSH_BIN is set; otherwise skipped).
 */

import * as path from 'path';
import * as fs from 'fs';
import { spawnSync, SpawnSyncReturns } from 'child_process';
import { generateFixtures, alteraFixtures, hwTclFiles, Fixture, FIXTURE_BASE } from './generator';
import { guardTier2 } from './tier';

const REPO_ROOT = path.resolve(__dirname, '../../..');
const DOCKER_IMAGE = process.env.QUARTUS_DOCKER_IMAGE ?? 'cvsoc/quartus:23.1';

// Docker paths (container-internal)
const DOCKER_TCLSH = '/opt/intelFPGA/quartus/bin/tclsh';
const DOCKER_VALIDATE_TCL = '/work/scripts/integration/quartus/validate.tcl';
const DOCKER_VALIDATE_PD_SH = '/work/scripts/integration/quartus/validate_pd.sh';
const DOCKER_COMPILE_TCL = '/work/scripts/integration/quartus/run_compile.tcl';

// Native paths (host filesystem)
const QUARTUS_TCLSH_BIN = process.env['QUARTUS_TCLSH_BIN'];
const QUARTUS_SH_BIN = process.env['QUARTUS_SH_BIN'];
const LOCAL_VALIDATE_TCL = path.resolve(REPO_ROOT, 'scripts/integration/quartus/validate.tcl');
const LOCAL_COMPILE_TCL = path.resolve(REPO_ROOT, 'scripts/integration/quartus/run_compile.tcl');

type RunMode = 'docker' | 'native';

function dockerImageAvailable(image: string): boolean {
  const result = spawnSync('docker', ['image', 'inspect', image], { encoding: 'utf8' });
  return !result.error && result.status === 0;
}

/**
 * Resolves which execution mode to use for this test run.
 *
 * Returns 'docker' if the Docker image is present and SKIP_DOCKER is not set.
 * Returns 'native' if QUARTUS_TCLSH_BIN is set (Docker absent or skipped).
 * Returns null if neither is available; callers should skip or throw.
 */
function resolveRunMode(): RunMode | null {
  const skipDocker = process.env['SKIP_DOCKER'] === '1';
  if (!skipDocker && dockerImageAvailable(DOCKER_IMAGE)) {
    return 'docker';
  }
  if (QUARTUS_TCLSH_BIN) {
    return 'native';
  }
  return null;
}

/**
 * Guard that replaces guardTier1('docker', ...) for the combined docker/native
 * toolset.  Returns true (caller must return) when neither mode is available
 * and SKIP_DOCKER=1 suppresses the error; throws when SKIP_DOCKER is not set.
 */
function guardQuartusToolset(): boolean {
  const mode = resolveRunMode();
  if (mode !== null) {
    return false; // toolset available — proceed
  }
  if (process.env['SKIP_DOCKER'] === '1') {
    console.warn(
      '[tier 1] SKIPPING quartus tests: Docker not available and QUARTUS_TCLSH_BIN is not set.'
    );
    return true; // skip
  }
  throw new Error(
    `[tier 1] Quartus tests require Docker (image: ${DOCKER_IMAGE}) or native binaries.\n` +
      `  Install Docker with the Quartus image, or set QUARTUS_TCLSH_BIN and QUARTUS_SH_BIN\n` +
      `  to point to a host-installed Quartus.  Use SKIP_DOCKER=1 to skip this suite.`
  );
}

let alteras: Fixture[] = [];

beforeAll(async () => {
  const all = await generateFixtures();
  alteras = alteraFixtures(all);
}, 300_000);

it('generates at least one Altera fixture with _hw.tcl', () => {
  expect(alteras.length).toBeGreaterThan(0);
});

it('all Altera _hw.tcl files pass Platform Designer stub validation', () => {
  if (guardQuartusToolset()) {
    return;
  }

  if (alteras.length === 0) {
    throw new Error('No Altera fixtures were generated — check generator output');
  }

  const mode = resolveRunMode()!;
  let result: SpawnSyncReturns<string>;

  if (mode === 'docker') {
    // Collect container-relative paths (/work mount)
    const hwTclEntries: Array<{ fixture: string; tcl: string }> = [];
    for (const fixture of alteras) {
      for (const tcl of hwTclFiles(fixture)) {
        hwTclEntries.push({ fixture: fixture.name, tcl: tcl.replace(REPO_ROOT, '/work') });
      }
    }
    if (hwTclEntries.length === 0) {
      throw new Error('Altera fixtures exist but hwTclFiles() returned nothing');
    }
    const tclPaths = hwTclEntries.map((e) => e.tcl);

    result = spawnSync(
      'docker',
      [
        'run',
        '--rm',
        '--user',
        `${process.getuid!()}:${process.getgid!()}`,
        '-v',
        `${REPO_ROOT}:/work`,
        '-v',
        `${FIXTURE_BASE}:${FIXTURE_BASE}`,
        DOCKER_IMAGE,
        DOCKER_TCLSH,
        DOCKER_VALIDATE_TCL,
        ...tclPaths,
      ],
      { encoding: 'utf8', timeout: 120_000 }
    );

    if (result.error) {
      throw new Error(`Failed to spawn Docker — ${result.error.message}`);
    }

    // eslint-disable-next-line no-console
    console.log(`  PASS: ${tclPaths.length} hw.tcl file(s) validated`);
  } else {
    // Native mode — pass actual host paths; no volume mapping needed
    const localTclPaths = alteras.flatMap((f) => hwTclFiles(f));
    if (localTclPaths.length === 0) {
      throw new Error('Altera fixtures exist but hwTclFiles() returned nothing');
    }

    result = spawnSync(QUARTUS_TCLSH_BIN!, [LOCAL_VALIDATE_TCL, ...localTclPaths], {
      encoding: 'utf8',
      timeout: 120_000,
    });

    if (result.error) {
      throw new Error(`Failed to spawn Quartus tclsh — ${result.error.message}`);
    }

    // eslint-disable-next-line no-console
    console.log(`  PASS: ${localTclPaths.length} hw.tcl file(s) validated (native)`);
  }

  const output = (result.stdout ?? '') + (result.stderr ?? '');
  const passed = result.status === 0 && output.includes('OVERALL PASS');

  if (!passed) {
    throw new Error(
      [
        `Quartus hw.tcl validation FAILED (exit ${result.status})`,
        `stdout:\n${result.stdout}`,
        `stderr:\n${result.stderr}`,
      ].join('\n')
    );
  }
});

it('all Altera _hw.tcl files pass Platform Designer BFM testbench validation', () => {
  if (guardQuartusToolset()) {
    return;
  }

  if (alteras.length === 0) {
    throw new Error('No Altera fixtures were generated — check generator output');
  }

  const mode = resolveRunMode()!;

  if (mode === 'native') {
    // qsys-generate is only available in the full Platform Designer suite.
    // A lite Quartus install does not include it; skip as tier 2.
    if (
      guardTier2(
        'qsys_generate',
        () => false,
        'qsys-generate is not available in native (lite) Quartus install'
      )
    ) {
      return;
    }
  }

  const tclPaths = alteras.flatMap((f) => hwTclFiles(f)).map((p) => p.replace(REPO_ROOT, '/work'));

  if (tclPaths.length === 0) {
    throw new Error('Altera fixtures exist but hwTclFiles() returned nothing');
  }

  const result = spawnSync(
    'docker',
    [
      'run',
      '--rm',
      '--user',
      `${process.getuid!()}:${process.getgid!()}`,
      '-v',
      `${REPO_ROOT}:/work`,
      '-v',
      `${FIXTURE_BASE}:${FIXTURE_BASE}`,
      DOCKER_IMAGE,
      'bash',
      DOCKER_VALIDATE_PD_SH,
      ...tclPaths,
    ],
    { encoding: 'utf8', timeout: 300_000 }
  );

  if (result.error) {
    throw new Error(`Failed to spawn Docker — ${result.error.message}`);
  }

  // Exit code 2 means qsys-generate was not found inside the Docker image.
  if (result.status === 2) {
    const output = (result.stdout ?? '') + (result.stderr ?? '');
    if (
      guardTier2(
        'qsys_generate',
        () => false,
        `qsys-generate not available in ${DOCKER_IMAGE}:\n${output}`
      )
    ) {
      return;
    }
  }

  const output = (result.stdout ?? '') + (result.stderr ?? '');
  const passed = result.status === 0 && output.includes('OVERALL PASS');

  if (!passed) {
    throw new Error(
      [
        `Platform Designer qsys-generate validation FAILED (exit ${result.status})`,
        `stdout:\n${result.stdout}`,
        `stderr:\n${result.stderr}`,
      ].join('\n')
    );
  }

  // eslint-disable-next-line no-console
  console.log(`  PASS: ${tclPaths.length} hw.tcl file(s) validated via BFM testbench`);
});

it('all Altera Quartus project creation scripts run successfully', () => {
  if (guardQuartusToolset()) {
    return;
  }

  if (alteras.length === 0) {
    throw new Error('No Altera fixtures were generated — check generator output');
  }

  const mode = resolveRunMode()!;

  for (const fixture of alteras) {
    const alteraDir = path.join(fixture.outputDir, 'altera');
    if (!fs.existsSync(alteraDir)) {
      continue;
    }
    const files = fs.readdirSync(alteraDir);
    const projectTclFile = files.find((f) => f.endsWith('_project.tcl'));
    if (!projectTclFile) {
      continue;
    }
    const projectTcl = path.join(alteraDir, projectTclFile);

    let result: SpawnSyncReturns<string>;

    if (mode === 'docker') {
      const tclInContainer = projectTcl.replace(REPO_ROOT, '/work');
      // quartus_sh needs a writable home for its cache; run as root (no --user)
      result = spawnSync(
        'docker',
        [
          'run',
          '--rm',
          '-v',
          `${REPO_ROOT}:/work`,
          '-v',
          `${FIXTURE_BASE}:${FIXTURE_BASE}`,
          DOCKER_IMAGE,
          '/opt/intelFPGA/quartus/bin/quartus_sh',
          '-t',
          tclInContainer,
        ],
        { encoding: 'utf8', timeout: 30_000, cwd: alteraDir }
      );
      if (result.error) {
        throw new Error(`Failed to spawn Docker for ${fixture.name} — ${result.error.message}`);
      }
    } else {
      result = spawnSync(QUARTUS_SH_BIN!, ['-t', projectTcl], {
        encoding: 'utf8',
        timeout: 30_000,
        cwd: alteraDir,
      });
      if (result.error) {
        throw new Error(`Failed to spawn quartus_sh for ${fixture.name} — ${result.error.message}`);
      }
    }

    if (result.status !== 0) {
      throw new Error(
        [
          `Quartus project creation FAILED for ${fixture.name} (exit ${result.status})`,
          `stdout:\n${result.stdout}`,
          `stderr:\n${result.stderr}`,
        ].join('\n')
      );
    }
    // eslint-disable-next-line no-console
    console.log(`  PASS: Quartus project for ${fixture.name}`);
  }
});

const compileTargetNames = new Set([
  'minimal_vhdl',
  'minimal_sv',
  'avalon_peripheral_vhdl',
  'avalon_peripheral_sv',
  'basic_vhdl',
  'basic_sv',
  'examples/basic_peripheral_vhdl',
  'examples/basic_peripheral_sv',
  'examples/comprehensive_avalon_vhdl',
  'examples/comprehensive_avalon_sv',
]);

it('representative Quartus projects compile successfully', () => {
  if (guardQuartusToolset()) {
    return;
  }

  const targets = alteras.filter((f) => compileTargetNames.has(f.name));
  if (targets.length === 0) {
    throw new Error(
      'No compile targets found. Expected at least one of: ' + [...compileTargetNames].join(', ')
    );
  }

  const mode = resolveRunMode()!;
  const failures: string[] = [];

  for (const fixture of targets) {
    const alteraDir = path.join(fixture.outputDir, 'altera');
    if (!fs.existsSync(alteraDir)) {
      failures.push(`${fixture.name}: altera directory not found`);
      continue;
    }
    const files = fs.readdirSync(alteraDir);
    const qpfFile = files.find((f) => f.endsWith('.qpf'));
    if (!qpfFile) {
      failures.push(`${fixture.name}: .qpf project file not found`);
      continue;
    }
    const projectName = qpfFile.replace('.qpf', '');

    let result: SpawnSyncReturns<string>;

    if (mode === 'docker') {
      const alteraDirInContainer = alteraDir.replace(REPO_ROOT, '/work');
      result = spawnSync(
        'docker',
        [
          'run',
          '--rm',
          '-v',
          `${REPO_ROOT}:/work`,
          '-v',
          `${FIXTURE_BASE}:${FIXTURE_BASE}`,
          DOCKER_IMAGE,
          '/opt/intelFPGA/quartus/bin/quartus_sh',
          '-t',
          DOCKER_COMPILE_TCL,
          alteraDirInContainer,
          projectName,
        ],
        { encoding: 'utf8', timeout: 600_000 }
      );
      if (result.error) {
        failures.push(`${fixture.name}: failed to spawn Docker — ${result.error.message}`);
        continue;
      }
    } else {
      result = spawnSync(QUARTUS_SH_BIN!, ['-t', LOCAL_COMPILE_TCL, alteraDir, projectName], {
        encoding: 'utf8',
        timeout: 600_000,
      });
      if (result.error) {
        failures.push(`${fixture.name}: failed to spawn quartus_sh — ${result.error.message}`);
        continue;
      }
    }

    if (result.status !== 0) {
      failures.push(
        [
          `${fixture.name}: Quartus compile FAIL (exit ${result.status})`,
          `stdout:\n${result.stdout}`,
          `stderr:\n${result.stderr}`,
        ].join('\n')
      );
    } else {
      // eslint-disable-next-line no-console
      console.log(`  PASS: Quartus compile for ${fixture.name}`);
    }
  }

  if (failures.length > 0) {
    throw new Error(
      `Quartus compile failed for ${failures.length} of ${targets.length} fixture(s):\n\n` +
        failures.join('\n\n---\n\n')
    );
  }
});
