/**
 * Quartus integration tests.
 *
 * Two levels of hw.tcl validation, both run inside cvsoc/quartus:23.1 via Docker:
 *
 *   1. Stub validation (tier 1 on Docker): tclsh validate.tcl — sources each
 *      _hw.tcl with Platform Designer API stubs, calls elaborate/validate
 *      callbacks, and checks structural correctness.  Fast (~ms per file).
 *
 *   2. BFM testbench validation (tier 1 on Docker, tier 2 on qsys-generate):
 *      validate_pd.sh — uses the companion test.qsys generated by IPCraft (which
 *      instantiates the component with all interfaces exported to the system
 *      boundary) and runs qsys-generate --testbench=STANDARD.  With all interfaces
 *      exported, Platform Designer's system validation passes and the BFM generator
 *      can auto-connect clock/reset/Avalon/AXI/conduit BFMs to each export.  This
 *      avoids "must be connected" false positives and catches real interface errors
 *      such as AXI-stream port role mismatches.  Slower (~30s per file).
 *      Set REQUIRE_QSYS_GENERATE=1 to fail instead of skip when qsys-generate
 *      is absent from the image.
 *
 * The Quartus-dependent tests self-skip when Docker or the image is not
 * available, so `npm run test:integration` works on machines without vendor
 * tools.  Set SKIP_DOCKER=1 to skip even when Docker is available.
 */

import * as path from 'path';
import * as fs from 'fs';
import { spawnSync } from 'child_process';
import { generateFixtures, alteraFixtures, hwTclFiles, Fixture, FIXTURE_BASE } from './generator';
import { guardTier1, guardTier2 } from './tier';

const REPO_ROOT = path.resolve(__dirname, '../../..');
const DOCKER_IMAGE = process.env.QUARTUS_DOCKER_IMAGE ?? 'cvsoc/quartus:23.1';
const TCLSH = '/opt/intelFPGA/quartus/bin/tclsh';
const VALIDATE_TCL = '/work/scripts/integration/quartus/validate.tcl';
const VALIDATE_PD_SH = '/work/scripts/integration/quartus/validate_pd.sh';

function dockerImageAvailable(image: string): boolean {
  const result = spawnSync('docker', ['image', 'inspect', image], { encoding: 'utf8' });
  return !result.error && result.status === 0;
}

let alteras: Fixture[] = [];

beforeAll(async () => {
  const all = await generateFixtures();
  alteras = alteraFixtures(all);
}, 300_000);

it('generates at least one Altera fixture with _hw.tcl', () => {
  expect(alteras.length).toBeGreaterThan(0);
});

it('all Altera _hw.tcl files pass Platform Designer stub validation', () => {
  if (guardTier1('docker', () => dockerImageAvailable(DOCKER_IMAGE))) {
    return;
  }

  if (alteras.length === 0) {
    throw new Error('No Altera fixtures were generated — check generator output');
  }

  // Collect all hw.tcl paths, mapped to their fixture name for reporting
  const hwTclEntries: Array<{ fixture: string; tcl: string }> = [];
  for (const fixture of alteras) {
    for (const tcl of hwTclFiles(fixture)) {
      // Path inside the container — replace host prefix with /work mount
      const tclInContainer = tcl.replace(REPO_ROOT, '/work');
      hwTclEntries.push({ fixture: fixture.name, tcl: tclInContainer });
    }
  }

  if (hwTclEntries.length === 0) {
    throw new Error('Altera fixtures exist but hwTclFiles() returned nothing');
  }

  const tclPaths = hwTclEntries.map((e) => e.tcl);

  const result = spawnSync(
    'docker',
    [
      'run',
      '--rm',
      '--user',
      `${process.getuid!()}:${process.getgid!()}`,
      '-v',
      `${REPO_ROOT}:/work`,
      // Mount the tmp fixture output dir as well (same path inside container)
      '-v',
      `${FIXTURE_BASE}:${FIXTURE_BASE}`,
      DOCKER_IMAGE,
      TCLSH,
      VALIDATE_TCL,
      ...tclPaths,
    ],
    { encoding: 'utf8', timeout: 120_000 }
  );

  if (result.error) {
    throw new Error(`Failed to spawn Docker — ${result.error.message}`);
  }

  const output = (result.stdout ?? '') + (result.stderr ?? '');
  const passed = result.status === 0 && output.includes('OVERALL PASS');

  if (!passed) {
    throw new Error(
      [
        `Quartus hw.tcl validation FAILED (exit ${result.status})`,
        `stdout:\n${result.stdout}`,
        `stderr:\n${result.stderr}`,
      ].join('\n')
    );
  }

  // eslint-disable-next-line no-console
  console.log(`  PASS: ${hwTclEntries.length} hw.tcl file(s) validated`);
});

it('all Altera _hw.tcl files pass Platform Designer BFM testbench validation', () => {
  // Requires Docker with the Quartus image AND qsys-generate inside it.
  // Uses test.qsys (generated by IPCraft with all interfaces exported) and runs
  // qsys-generate --testbench=STANDARD.  With all interfaces at the system
  // boundary, Platform Designer's validator is satisfied and the BFM generator
  // auto-connects BFMs — catching real interface errors such as AXI-stream port
  // role mismatches without "must be connected" false positives.
  //
  // Tier 1 on Docker; tier 2 on qsys-generate (may not be present in the image).
  // Set REQUIRE_QSYS_GENERATE=1 to fail instead of skip when the tool is absent.
  if (guardTier1('docker', () => dockerImageAvailable(DOCKER_IMAGE))) {
    return;
  }

  if (alteras.length === 0) {
    throw new Error('No Altera fixtures were generated — check generator output');
  }

  const tclPaths = alteras.flatMap((f) => hwTclFiles(f)).map((p) => p.replace(REPO_ROOT, '/work'));

  if (tclPaths.length === 0) {
    throw new Error('Altera fixtures exist but hwTclFiles() returned nothing');
  }

  const result = spawnSync(
    'docker',
    [
      'run',
      '--rm',
      '--user',
      `${process.getuid!()}:${process.getgid!()}`,
      '-v',
      `${REPO_ROOT}:/work`,
      '-v',
      `${FIXTURE_BASE}:${FIXTURE_BASE}`,
      DOCKER_IMAGE,
      'bash',
      VALIDATE_PD_SH,
      ...tclPaths,
    ],
    { encoding: 'utf8', timeout: 300_000 }
  );

  if (result.error) {
    throw new Error(`Failed to spawn Docker — ${result.error.message}`);
  }

  // Exit code 2 means qsys-generate was not found inside the Docker image.
  if (result.status === 2) {
    const output = (result.stdout ?? '') + (result.stderr ?? '');
    if (
      guardTier2(
        'qsys_generate',
        () => false,
        `qsys-generate not available in ${DOCKER_IMAGE}:\n${output}`
      )
    ) {
      return;
    }
  }

  const output = (result.stdout ?? '') + (result.stderr ?? '');
  const passed = result.status === 0 && output.includes('OVERALL PASS');

  if (!passed) {
    throw new Error(
      [
        `Platform Designer qsys-generate validation FAILED (exit ${result.status})`,
        `stdout:\n${result.stdout}`,
        `stderr:\n${result.stderr}`,
      ].join('\n')
    );
  }

  // eslint-disable-next-line no-console
  console.log(`  PASS: ${tclPaths.length} hw.tcl file(s) validated via BFM testbench`);
});

it('all Altera Quartus project creation scripts run successfully', () => {
  if (guardTier1('docker', () => dockerImageAvailable(DOCKER_IMAGE))) {
    return;
  }

  if (alteras.length === 0) {
    throw new Error('No Altera fixtures were generated — check generator output');
  }

  for (const fixture of alteras) {
    const alteraDir = path.join(fixture.outputDir, 'altera');
    if (!fs.existsSync(alteraDir)) {
      continue;
    }
    const files = fs.readdirSync(alteraDir);
    const projectTclFile = files.find((f) => f.endsWith('_project.tcl'));
    if (!projectTclFile) {
      continue;
    }
    const projectTcl = path.join(alteraDir, projectTclFile);

    const tclInContainer = projectTcl.replace(REPO_ROOT, '/work');
    // quartus_sh needs a writable home directory for its cache/init; run as
    // root (no --user) so the image's default HOME works. The container is
    // --rm so nothing persists after the run.
    const result = spawnSync(
      'docker',
      [
        'run',
        '--rm',
        '-v',
        `${REPO_ROOT}:/work`,
        '-v',
        `${FIXTURE_BASE}:${FIXTURE_BASE}`,
        DOCKER_IMAGE,
        '/opt/intelFPGA/quartus/bin/quartus_sh',
        '-t',
        tclInContainer,
      ],
      { encoding: 'utf8', timeout: 30_000, cwd: alteraDir }
    );

    if (result.error) {
      throw new Error(`Failed to spawn Docker for ${fixture.name} — ${result.error.message}`);
    }

    if (result.status !== 0) {
      throw new Error(
        [
          `Quartus project creation FAILED for ${fixture.name} (exit ${result.status})`,
          `stdout:\n${result.stdout}`,
          `stderr:\n${result.stderr}`,
        ].join('\n')
      );
    }
    // eslint-disable-next-line no-console
    console.log(`  PASS: Quartus project for ${fixture.name}`);
  }
});

const COMPILE_TCL = '/work/scripts/integration/quartus/run_compile.tcl';

const compileTargetNames = new Set([
  'minimal_vhdl',
  'minimal_sv',
  'avalon_peripheral_vhdl',
  'avalon_peripheral_sv',
  'basic_vhdl',
  'basic_sv',
  'examples/basic_peripheral_vhdl',
  'examples/basic_peripheral_sv',
  'examples/comprehensive_avalon_vhdl',
  'examples/comprehensive_avalon_sv',
]);

it('representative Quartus projects compile successfully', () => {
  if (guardTier1('docker', () => dockerImageAvailable(DOCKER_IMAGE))) {
    return;
  }

  const targets = alteras.filter((f) => compileTargetNames.has(f.name));
  if (targets.length === 0) {
    throw new Error(
      'No compile targets found. Expected at least one of: ' + [...compileTargetNames].join(', ')
    );
  }

  const failures: string[] = [];

  for (const fixture of targets) {
    const alteraDir = path.join(fixture.outputDir, 'altera');
    if (!fs.existsSync(alteraDir)) {
      failures.push(`${fixture.name}: altera directory not found`);
      continue;
    }
    const files = fs.readdirSync(alteraDir);
    const qpfFile = files.find((f) => f.endsWith('.qpf'));
    if (!qpfFile) {
      failures.push(`${fixture.name}: .qpf project file not found`);
      continue;
    }
    const projectName = qpfFile.replace('.qpf', '');
    const alteraDirInContainer = alteraDir.replace(REPO_ROOT, '/work');

    const result = spawnSync(
      'docker',
      [
        'run',
        '--rm',
        '-v',
        `${REPO_ROOT}:/work`,
        '-v',
        `${FIXTURE_BASE}:${FIXTURE_BASE}`,
        DOCKER_IMAGE,
        '/opt/intelFPGA/quartus/bin/quartus_sh',
        '-t',
        COMPILE_TCL,
        alteraDirInContainer,
        projectName,
      ],
      { encoding: 'utf8', timeout: 600_000 }
    );

    if (result.error) {
      failures.push(`${fixture.name}: failed to spawn Docker — ${result.error.message}`);
      continue;
    }

    if (result.status !== 0) {
      failures.push(
        [
          `${fixture.name}: Quartus compile FAIL (exit ${result.status})`,
          `stdout:\n${result.stdout}`,
          `stderr:\n${result.stderr}`,
        ].join('\n')
      );
    } else {
      // eslint-disable-next-line no-console
      console.log(`  PASS: Quartus compile for ${fixture.name}`);
    }
  }

  if (failures.length > 0) {
    throw new Error(
      `Quartus compile failed for ${failures.length} of ${targets.length} fixture(s):\n\n` +
        failures.join('\n\n---\n\n')
    );
  }
});
